// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package challenge

import (
	"context"
	"sync"

	"github.com/TiraelSedai/PhotoChallengeBot/internal/repository"
)

// Ensure that MoqStore does implement store.
// If this is not the case, regenerate this file with mockery.
var _ store = &MoqStore{}

// MoqStore is a mock implementation of store.
//
//	func TestSomethingThatUsesstore(t *testing.T) {
//
//		// make and configure a mocked store
//		mockedstore := &MoqStore{
//			CreateFunc: func(context1 context.Context, createChallengeInput repository.CreateChallengeInput) (repository.Challenge, error) {
//				panic("mock out the Create method")
//			},
//			FindOpenByMainChatIDFunc: func(context1 context.Context, n int64) (*repository.Challenge, error) {
//				panic("mock out the FindOpenByMainChatID method")
//			},
//			NextNumFunc: func(context1 context.Context, n int64) (int, error) {
//				panic("mock out the NextNum method")
//			},
//		}
//
//		// use mockedstore in code that requires store
//		// and then make assertions.
//
//	}
type MoqStore struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(context1 context.Context, createChallengeInput repository.CreateChallengeInput) (repository.Challenge, error)

	// FindOpenByMainChatIDFunc mocks the FindOpenByMainChatID method.
	FindOpenByMainChatIDFunc func(context1 context.Context, n int64) (*repository.Challenge, error)

	// NextNumFunc mocks the NextNum method.
	NextNumFunc func(context1 context.Context, n int64) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// CreateChallengeInput is the createChallengeInput argument value.
			CreateChallengeInput repository.CreateChallengeInput
		}
		// FindOpenByMainChatID holds details about calls to the FindOpenByMainChatID method.
		FindOpenByMainChatID []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
		}
		// NextNum holds details about calls to the NextNum method.
		NextNum []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
		}
	}
	lockCreate               sync.RWMutex
	lockFindOpenByMainChatID sync.RWMutex
	lockNextNum              sync.RWMutex
}

// Create calls CreateFunc.
func (mock *MoqStore) Create(context1 context.Context, createChallengeInput repository.CreateChallengeInput) (repository.Challenge, error) {
	callInfo := struct {
		Context1             context.Context
		CreateChallengeInput repository.CreateChallengeInput
	}{
		Context1:             context1,
		CreateChallengeInput: createChallengeInput,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	if mock.CreateFunc == nil {
		var (
			challenge repository.Challenge
			err       error
		)
		return challenge, err
	}
	return mock.CreateFunc(context1, createChallengeInput)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedstore.CreateCalls())
func (mock *MoqStore) CreateCalls() []struct {
	Context1             context.Context
	CreateChallengeInput repository.CreateChallengeInput
} {
	var calls []struct {
		Context1             context.Context
		CreateChallengeInput repository.CreateChallengeInput
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// FindOpenByMainChatID calls FindOpenByMainChatIDFunc.
func (mock *MoqStore) FindOpenByMainChatID(context1 context.Context, n int64) (*repository.Challenge, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
	}{
		Context1: context1,
		N:        n,
	}
	mock.lockFindOpenByMainChatID.Lock()
	mock.calls.FindOpenByMainChatID = append(mock.calls.FindOpenByMainChatID, callInfo)
	mock.lockFindOpenByMainChatID.Unlock()
	if mock.FindOpenByMainChatIDFunc == nil {
		var (
			challenge *repository.Challenge
			err       error
		)
		return challenge, err
	}
	return mock.FindOpenByMainChatIDFunc(context1, n)
}

// FindOpenByMainChatIDCalls gets all the calls that were made to FindOpenByMainChatID.
// Check the length with:
//
//	len(mockedstore.FindOpenByMainChatIDCalls())
func (mock *MoqStore) FindOpenByMainChatIDCalls() []struct {
	Context1 context.Context
	N        int64
} {
	var calls []struct {
		Context1 context.Context
		N        int64
	}
	mock.lockFindOpenByMainChatID.RLock()
	calls = mock.calls.FindOpenByMainChatID
	mock.lockFindOpenByMainChatID.RUnlock()
	return calls
}

// NextNum calls NextNumFunc.
func (mock *MoqStore) NextNum(context1 context.Context, n int64) (int, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
	}{
		Context1: context1,
		N:        n,
	}
	mock.lockNextNum.Lock()
	mock.calls.NextNum = append(mock.calls.NextNum, callInfo)
	mock.lockNextNum.Unlock()
	if mock.NextNumFunc == nil {
		var (
			n1  int
			err error
		)
		return n1, err
	}
	return mock.NextNumFunc(context1, n)
}

// NextNumCalls gets all the calls that were made to NextNum.
// Check the length with:
//
//	len(mockedstore.NextNumCalls())
func (mock *MoqStore) NextNumCalls() []struct {
	Context1 context.Context
	N        int64
} {
	var calls []struct {
		Context1 context.Context
		N        int64
	}
	mock.lockNextNum.RLock()
	calls = mock.calls.NextNum
	mock.lockNextNum.RUnlock()
	return calls
}
