// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package tg

import (
	"context"
	"sync"

	"github.com/go-telegram/bot"
	"github.com/go-telegram/bot/models"
)

// Ensure that MoqClient does implement client.
// If this is not the case, regenerate this file with mockery.
var _ client = &MoqClient{}

// MoqClient is a mock implementation of client.
//
//	func TestSomethingThatUsesclient(t *testing.T) {
//
//		// make and configure a mocked client
//		mockedclient := &MoqClient{
//			AnswerCallbackQueryFunc: func(context1 context.Context, answerCallbackQueryParams *bot.AnswerCallbackQueryParams) (bool, error) {
//				panic("mock out the AnswerCallbackQuery method")
//			},
//			EditMessageMediaFunc: func(context1 context.Context, editMessageMediaParams *bot.EditMessageMediaParams) (*models.Message, error) {
//				panic("mock out the EditMessageMedia method")
//			},
//			GetChatMemberFunc: func(context1 context.Context, getChatMemberParams *bot.GetChatMemberParams) (*models.ChatMember, error) {
//				panic("mock out the GetChatMember method")
//			},
//			GetMeFunc: func(context1 context.Context) (*models.User, error) {
//				panic("mock out the GetMe method")
//			},
//			PinChatMessageFunc: func(context1 context.Context, pinChatMessageParams *bot.PinChatMessageParams) (bool, error) {
//				panic("mock out the PinChatMessage method")
//			},
//			SendMediaGroupFunc: func(context1 context.Context, sendMediaGroupParams *bot.SendMediaGroupParams) ([]*models.Message, error) {
//				panic("mock out the SendMediaGroup method")
//			},
//			SendMessageFunc: func(context1 context.Context, sendMessageParams *bot.SendMessageParams) (*models.Message, error) {
//				panic("mock out the SendMessage method")
//			},
//			SendPhotoFunc: func(context1 context.Context, sendPhotoParams *bot.SendPhotoParams) (*models.Message, error) {
//				panic("mock out the SendPhoto method")
//			},
//			StartFunc: func(context1 context.Context)  {
//				panic("mock out the Start method")
//			},
//		}
//
//		// use mockedclient in code that requires client
//		// and then make assertions.
//
//	}
type MoqClient struct {
	// AnswerCallbackQueryFunc mocks the AnswerCallbackQuery method.
	AnswerCallbackQueryFunc func(context1 context.Context, answerCallbackQueryParams *bot.AnswerCallbackQueryParams) (bool, error)

	// EditMessageMediaFunc mocks the EditMessageMedia method.
	EditMessageMediaFunc func(context1 context.Context, editMessageMediaParams *bot.EditMessageMediaParams) (*models.Message, error)

	// GetChatMemberFunc mocks the GetChatMember method.
	GetChatMemberFunc func(context1 context.Context, getChatMemberParams *bot.GetChatMemberParams) (*models.ChatMember, error)

	// GetMeFunc mocks the GetMe method.
	GetMeFunc func(context1 context.Context) (*models.User, error)

	// PinChatMessageFunc mocks the PinChatMessage method.
	PinChatMessageFunc func(context1 context.Context, pinChatMessageParams *bot.PinChatMessageParams) (bool, error)

	// SendMediaGroupFunc mocks the SendMediaGroup method.
	SendMediaGroupFunc func(context1 context.Context, sendMediaGroupParams *bot.SendMediaGroupParams) ([]*models.Message, error)

	// SendMessageFunc mocks the SendMessage method.
	SendMessageFunc func(context1 context.Context, sendMessageParams *bot.SendMessageParams) (*models.Message, error)

	// SendPhotoFunc mocks the SendPhoto method.
	SendPhotoFunc func(context1 context.Context, sendPhotoParams *bot.SendPhotoParams) (*models.Message, error)

	// StartFunc mocks the Start method.
	StartFunc func(context1 context.Context)

	// calls tracks calls to the methods.
	calls struct {
		// AnswerCallbackQuery holds details about calls to the AnswerCallbackQuery method.
		AnswerCallbackQuery []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// AnswerCallbackQueryParams is the answerCallbackQueryParams argument value.
			AnswerCallbackQueryParams *bot.AnswerCallbackQueryParams
		}
		// EditMessageMedia holds details about calls to the EditMessageMedia method.
		EditMessageMedia []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// EditMessageMediaParams is the editMessageMediaParams argument value.
			EditMessageMediaParams *bot.EditMessageMediaParams
		}
		// GetChatMember holds details about calls to the GetChatMember method.
		GetChatMember []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// GetChatMemberParams is the getChatMemberParams argument value.
			GetChatMemberParams *bot.GetChatMemberParams
		}
		// GetMe holds details about calls to the GetMe method.
		GetMe []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
		}
		// PinChatMessage holds details about calls to the PinChatMessage method.
		PinChatMessage []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// PinChatMessageParams is the pinChatMessageParams argument value.
			PinChatMessageParams *bot.PinChatMessageParams
		}
		// SendMediaGroup holds details about calls to the SendMediaGroup method.
		SendMediaGroup []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// SendMediaGroupParams is the sendMediaGroupParams argument value.
			SendMediaGroupParams *bot.SendMediaGroupParams
		}
		// SendMessage holds details about calls to the SendMessage method.
		SendMessage []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// SendMessageParams is the sendMessageParams argument value.
			SendMessageParams *bot.SendMessageParams
		}
		// SendPhoto holds details about calls to the SendPhoto method.
		SendPhoto []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// SendPhotoParams is the sendPhotoParams argument value.
			SendPhotoParams *bot.SendPhotoParams
		}
		// Start holds details about calls to the Start method.
		Start []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
		}
	}
	lockAnswerCallbackQuery sync.RWMutex
	lockEditMessageMedia    sync.RWMutex
	lockGetChatMember       sync.RWMutex
	lockGetMe               sync.RWMutex
	lockPinChatMessage      sync.RWMutex
	lockSendMediaGroup      sync.RWMutex
	lockSendMessage         sync.RWMutex
	lockSendPhoto           sync.RWMutex
	lockStart               sync.RWMutex
}

// AnswerCallbackQuery calls AnswerCallbackQueryFunc.
func (mock *MoqClient) AnswerCallbackQuery(context1 context.Context, answerCallbackQueryParams *bot.AnswerCallbackQueryParams) (bool, error) {
	callInfo := struct {
		Context1                  context.Context
		AnswerCallbackQueryParams *bot.AnswerCallbackQueryParams
	}{
		Context1:                  context1,
		AnswerCallbackQueryParams: answerCallbackQueryParams,
	}
	mock.lockAnswerCallbackQuery.Lock()
	mock.calls.AnswerCallbackQuery = append(mock.calls.AnswerCallbackQuery, callInfo)
	mock.lockAnswerCallbackQuery.Unlock()
	if mock.AnswerCallbackQueryFunc == nil {
		var (
			b   bool
			err error
		)
		return b, err
	}
	return mock.AnswerCallbackQueryFunc(context1, answerCallbackQueryParams)
}

// AnswerCallbackQueryCalls gets all the calls that were made to AnswerCallbackQuery.
// Check the length with:
//
//	len(mockedclient.AnswerCallbackQueryCalls())
func (mock *MoqClient) AnswerCallbackQueryCalls() []struct {
	Context1                  context.Context
	AnswerCallbackQueryParams *bot.AnswerCallbackQueryParams
} {
	var calls []struct {
		Context1                  context.Context
		AnswerCallbackQueryParams *bot.AnswerCallbackQueryParams
	}
	mock.lockAnswerCallbackQuery.RLock()
	calls = mock.calls.AnswerCallbackQuery
	mock.lockAnswerCallbackQuery.RUnlock()
	return calls
}

// EditMessageMedia calls EditMessageMediaFunc.
func (mock *MoqClient) EditMessageMedia(context1 context.Context, editMessageMediaParams *bot.EditMessageMediaParams) (*models.Message, error) {
	callInfo := struct {
		Context1               context.Context
		EditMessageMediaParams *bot.EditMessageMediaParams
	}{
		Context1:               context1,
		EditMessageMediaParams: editMessageMediaParams,
	}
	mock.lockEditMessageMedia.Lock()
	mock.calls.EditMessageMedia = append(mock.calls.EditMessageMedia, callInfo)
	mock.lockEditMessageMedia.Unlock()
	if mock.EditMessageMediaFunc == nil {
		var (
			message *models.Message
			err     error
		)
		return message, err
	}
	return mock.EditMessageMediaFunc(context1, editMessageMediaParams)
}

// EditMessageMediaCalls gets all the calls that were made to EditMessageMedia.
// Check the length with:
//
//	len(mockedclient.EditMessageMediaCalls())
func (mock *MoqClient) EditMessageMediaCalls() []struct {
	Context1               context.Context
	EditMessageMediaParams *bot.EditMessageMediaParams
} {
	var calls []struct {
		Context1               context.Context
		EditMessageMediaParams *bot.EditMessageMediaParams
	}
	mock.lockEditMessageMedia.RLock()
	calls = mock.calls.EditMessageMedia
	mock.lockEditMessageMedia.RUnlock()
	return calls
}

// GetChatMember calls GetChatMemberFunc.
func (mock *MoqClient) GetChatMember(context1 context.Context, getChatMemberParams *bot.GetChatMemberParams) (*models.ChatMember, error) {
	callInfo := struct {
		Context1            context.Context
		GetChatMemberParams *bot.GetChatMemberParams
	}{
		Context1:            context1,
		GetChatMemberParams: getChatMemberParams,
	}
	mock.lockGetChatMember.Lock()
	mock.calls.GetChatMember = append(mock.calls.GetChatMember, callInfo)
	mock.lockGetChatMember.Unlock()
	if mock.GetChatMemberFunc == nil {
		var (
			chatMember *models.ChatMember
			err        error
		)
		return chatMember, err
	}
	return mock.GetChatMemberFunc(context1, getChatMemberParams)
}

// GetChatMemberCalls gets all the calls that were made to GetChatMember.
// Check the length with:
//
//	len(mockedclient.GetChatMemberCalls())
func (mock *MoqClient) GetChatMemberCalls() []struct {
	Context1            context.Context
	GetChatMemberParams *bot.GetChatMemberParams
} {
	var calls []struct {
		Context1            context.Context
		GetChatMemberParams *bot.GetChatMemberParams
	}
	mock.lockGetChatMember.RLock()
	calls = mock.calls.GetChatMember
	mock.lockGetChatMember.RUnlock()
	return calls
}

// GetMe calls GetMeFunc.
func (mock *MoqClient) GetMe(context1 context.Context) (*models.User, error) {
	callInfo := struct {
		Context1 context.Context
	}{
		Context1: context1,
	}
	mock.lockGetMe.Lock()
	mock.calls.GetMe = append(mock.calls.GetMe, callInfo)
	mock.lockGetMe.Unlock()
	if mock.GetMeFunc == nil {
		var (
			user *models.User
			err  error
		)
		return user, err
	}
	return mock.GetMeFunc(context1)
}

// GetMeCalls gets all the calls that were made to GetMe.
// Check the length with:
//
//	len(mockedclient.GetMeCalls())
func (mock *MoqClient) GetMeCalls() []struct {
	Context1 context.Context
} {
	var calls []struct {
		Context1 context.Context
	}
	mock.lockGetMe.RLock()
	calls = mock.calls.GetMe
	mock.lockGetMe.RUnlock()
	return calls
}

// PinChatMessage calls PinChatMessageFunc.
func (mock *MoqClient) PinChatMessage(context1 context.Context, pinChatMessageParams *bot.PinChatMessageParams) (bool, error) {
	callInfo := struct {
		Context1             context.Context
		PinChatMessageParams *bot.PinChatMessageParams
	}{
		Context1:             context1,
		PinChatMessageParams: pinChatMessageParams,
	}
	mock.lockPinChatMessage.Lock()
	mock.calls.PinChatMessage = append(mock.calls.PinChatMessage, callInfo)
	mock.lockPinChatMessage.Unlock()
	if mock.PinChatMessageFunc == nil {
		var (
			b   bool
			err error
		)
		return b, err
	}
	return mock.PinChatMessageFunc(context1, pinChatMessageParams)
}

// PinChatMessageCalls gets all the calls that were made to PinChatMessage.
// Check the length with:
//
//	len(mockedclient.PinChatMessageCalls())
func (mock *MoqClient) PinChatMessageCalls() []struct {
	Context1             context.Context
	PinChatMessageParams *bot.PinChatMessageParams
} {
	var calls []struct {
		Context1             context.Context
		PinChatMessageParams *bot.PinChatMessageParams
	}
	mock.lockPinChatMessage.RLock()
	calls = mock.calls.PinChatMessage
	mock.lockPinChatMessage.RUnlock()
	return calls
}

// SendMediaGroup calls SendMediaGroupFunc.
func (mock *MoqClient) SendMediaGroup(context1 context.Context, sendMediaGroupParams *bot.SendMediaGroupParams) ([]*models.Message, error) {
	callInfo := struct {
		Context1             context.Context
		SendMediaGroupParams *bot.SendMediaGroupParams
	}{
		Context1:             context1,
		SendMediaGroupParams: sendMediaGroupParams,
	}
	mock.lockSendMediaGroup.Lock()
	mock.calls.SendMediaGroup = append(mock.calls.SendMediaGroup, callInfo)
	mock.lockSendMediaGroup.Unlock()
	if mock.SendMediaGroupFunc == nil {
		var (
			messages []*models.Message
			err      error
		)
		return messages, err
	}
	return mock.SendMediaGroupFunc(context1, sendMediaGroupParams)
}

// SendMediaGroupCalls gets all the calls that were made to SendMediaGroup.
// Check the length with:
//
//	len(mockedclient.SendMediaGroupCalls())
func (mock *MoqClient) SendMediaGroupCalls() []struct {
	Context1             context.Context
	SendMediaGroupParams *bot.SendMediaGroupParams
} {
	var calls []struct {
		Context1             context.Context
		SendMediaGroupParams *bot.SendMediaGroupParams
	}
	mock.lockSendMediaGroup.RLock()
	calls = mock.calls.SendMediaGroup
	mock.lockSendMediaGroup.RUnlock()
	return calls
}

// SendMessage calls SendMessageFunc.
func (mock *MoqClient) SendMessage(context1 context.Context, sendMessageParams *bot.SendMessageParams) (*models.Message, error) {
	callInfo := struct {
		Context1          context.Context
		SendMessageParams *bot.SendMessageParams
	}{
		Context1:          context1,
		SendMessageParams: sendMessageParams,
	}
	mock.lockSendMessage.Lock()
	mock.calls.SendMessage = append(mock.calls.SendMessage, callInfo)
	mock.lockSendMessage.Unlock()
	if mock.SendMessageFunc == nil {
		var (
			message *models.Message
			err     error
		)
		return message, err
	}
	return mock.SendMessageFunc(context1, sendMessageParams)
}

// SendMessageCalls gets all the calls that were made to SendMessage.
// Check the length with:
//
//	len(mockedclient.SendMessageCalls())
func (mock *MoqClient) SendMessageCalls() []struct {
	Context1          context.Context
	SendMessageParams *bot.SendMessageParams
} {
	var calls []struct {
		Context1          context.Context
		SendMessageParams *bot.SendMessageParams
	}
	mock.lockSendMessage.RLock()
	calls = mock.calls.SendMessage
	mock.lockSendMessage.RUnlock()
	return calls
}

// SendPhoto calls SendPhotoFunc.
func (mock *MoqClient) SendPhoto(context1 context.Context, sendPhotoParams *bot.SendPhotoParams) (*models.Message, error) {
	callInfo := struct {
		Context1        context.Context
		SendPhotoParams *bot.SendPhotoParams
	}{
		Context1:        context1,
		SendPhotoParams: sendPhotoParams,
	}
	mock.lockSendPhoto.Lock()
	mock.calls.SendPhoto = append(mock.calls.SendPhoto, callInfo)
	mock.lockSendPhoto.Unlock()
	if mock.SendPhotoFunc == nil {
		var (
			message *models.Message
			err     error
		)
		return message, err
	}
	return mock.SendPhotoFunc(context1, sendPhotoParams)
}

// SendPhotoCalls gets all the calls that were made to SendPhoto.
// Check the length with:
//
//	len(mockedclient.SendPhotoCalls())
func (mock *MoqClient) SendPhotoCalls() []struct {
	Context1        context.Context
	SendPhotoParams *bot.SendPhotoParams
} {
	var calls []struct {
		Context1        context.Context
		SendPhotoParams *bot.SendPhotoParams
	}
	mock.lockSendPhoto.RLock()
	calls = mock.calls.SendPhoto
	mock.lockSendPhoto.RUnlock()
	return calls
}

// Start calls StartFunc.
func (mock *MoqClient) Start(context1 context.Context) {
	callInfo := struct {
		Context1 context.Context
	}{
		Context1: context1,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	if mock.StartFunc == nil {
		return
	}
	mock.StartFunc(context1)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//
//	len(mockedclient.StartCalls())
func (mock *MoqClient) StartCalls() []struct {
	Context1 context.Context
} {
	var calls []struct {
		Context1 context.Context
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}
