// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package vote

import (
	"context"
	"sync"

	"github.com/TiraelSedai/PhotoChallengeBot/internal/repository"
)

// Ensure that MoqChallengeStore does implement challengeStore.
// If this is not the case, regenerate this file with mockery.
var _ challengeStore = &MoqChallengeStore{}

// MoqChallengeStore is a mock implementation of challengeStore.
//
//	func TestSomethingThatUseschallengeStore(t *testing.T) {
//
//		// make and configure a mocked challengeStore
//		mockedchallengeStore := &MoqChallengeStore{
//			GetFunc: func(context1 context.Context, n int64) (repository.Challenge, error) {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedchallengeStore in code that requires challengeStore
//		// and then make assertions.
//
//	}
type MoqChallengeStore struct {
	// GetFunc mocks the Get method.
	GetFunc func(context1 context.Context, n int64) (repository.Challenge, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
		}
	}
	lockGet sync.RWMutex
}

// Get calls GetFunc.
func (mock *MoqChallengeStore) Get(context1 context.Context, n int64) (repository.Challenge, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
	}{
		Context1: context1,
		N:        n,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			challenge repository.Challenge
			err       error
		)
		return challenge, err
	}
	return mock.GetFunc(context1, n)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedchallengeStore.GetCalls())
func (mock *MoqChallengeStore) GetCalls() []struct {
	Context1 context.Context
	N        int64
} {
	var calls []struct {
		Context1 context.Context
		N        int64
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}
