// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package vote

import (
	"context"
	"sync"

	"github.com/go-telegram/bot/models"
)

// Ensure that MoqPublisher does implement publisher.
// If this is not the case, regenerate this file with mockery.
var _ publisher = &MoqPublisher{}

// MoqPublisher is a mock implementation of publisher.
//
//	func TestSomethingThatUsespublisher(t *testing.T) {
//
//		// make and configure a mocked publisher
//		mockedpublisher := &MoqPublisher{
//			AnswerCallbackFunc: func(context1 context.Context, s string, s1 string) error {
//				panic("mock out the AnswerCallback method")
//			},
//			EditPhotoFunc: func(context1 context.Context, n int64, n1 int, s string, s1 string, inlineKeyboardMarkup *models.InlineKeyboardMarkup) error {
//				panic("mock out the EditPhoto method")
//			},
//			SendPhotoFunc: func(context1 context.Context, n int64, s string, s1 string, inlineKeyboardMarkup *models.InlineKeyboardMarkup) (int, error) {
//				panic("mock out the SendPhoto method")
//			},
//			SendTextFunc: func(context1 context.Context, n int64, s string) (int, error) {
//				panic("mock out the SendText method")
//			},
//		}
//
//		// use mockedpublisher in code that requires publisher
//		// and then make assertions.
//
//	}
type MoqPublisher struct {
	// AnswerCallbackFunc mocks the AnswerCallback method.
	AnswerCallbackFunc func(context1 context.Context, s string, s1 string) error

	// EditPhotoFunc mocks the EditPhoto method.
	EditPhotoFunc func(context1 context.Context, n int64, n1 int, s string, s1 string, inlineKeyboardMarkup *models.InlineKeyboardMarkup) error

	// SendPhotoFunc mocks the SendPhoto method.
	SendPhotoFunc func(context1 context.Context, n int64, s string, s1 string, inlineKeyboardMarkup *models.InlineKeyboardMarkup) (int, error)

	// SendTextFunc mocks the SendText method.
	SendTextFunc func(context1 context.Context, n int64, s string) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// AnswerCallback holds details about calls to the AnswerCallback method.
		AnswerCallback []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
			// S1 is the s1 argument value.
			S1 string
		}
		// EditPhoto holds details about calls to the EditPhoto method.
		EditPhoto []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// N1 is the n1 argument value.
			N1 int
			// S is the s argument value.
			S string
			// S1 is the s1 argument value.
			S1 string
			// InlineKeyboardMarkup is the inlineKeyboardMarkup argument value.
			InlineKeyboardMarkup *models.InlineKeyboardMarkup
		}
		// SendPhoto holds details about calls to the SendPhoto method.
		SendPhoto []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// S is the s argument value.
			S string
			// S1 is the s1 argument value.
			S1 string
			// InlineKeyboardMarkup is the inlineKeyboardMarkup argument value.
			InlineKeyboardMarkup *models.InlineKeyboardMarkup
		}
		// SendText holds details about calls to the SendText method.
		SendText []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// S is the s argument value.
			S string
		}
	}
	lockAnswerCallback sync.RWMutex
	lockEditPhoto      sync.RWMutex
	lockSendPhoto      sync.RWMutex
	lockSendText       sync.RWMutex
}

// AnswerCallback calls AnswerCallbackFunc.
func (mock *MoqPublisher) AnswerCallback(context1 context.Context, s string, s1 string) error {
	callInfo := struct {
		Context1 context.Context
		S        string
		S1       string
	}{
		Context1: context1,
		S:        s,
		S1:       s1,
	}
	mock.lockAnswerCallback.Lock()
	mock.calls.AnswerCallback = append(mock.calls.AnswerCallback, callInfo)
	mock.lockAnswerCallback.Unlock()
	if mock.AnswerCallbackFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.AnswerCallbackFunc(context1, s, s1)
}

// AnswerCallbackCalls gets all the calls that were made to AnswerCallback.
// Check the length with:
//
//	len(mockedpublisher.AnswerCallbackCalls())
func (mock *MoqPublisher) AnswerCallbackCalls() []struct {
	Context1 context.Context
	S        string
	S1       string
} {
	var calls []struct {
		Context1 context.Context
		S        string
		S1       string
	}
	mock.lockAnswerCallback.RLock()
	calls = mock.calls.AnswerCallback
	mock.lockAnswerCallback.RUnlock()
	return calls
}

// EditPhoto calls EditPhotoFunc.
func (mock *MoqPublisher) EditPhoto(context1 context.Context, n int64, n1 int, s string, s1 string, inlineKeyboardMarkup *models.InlineKeyboardMarkup) error {
	callInfo := struct {
		Context1             context.Context
		N                    int64
		N1                   int
		S                    string
		S1                   string
		InlineKeyboardMarkup *models.InlineKeyboardMarkup
	}{
		Context1:             context1,
		N:                    n,
		N1:                   n1,
		S:                    s,
		S1:                   s1,
		InlineKeyboardMarkup: inlineKeyboardMarkup,
	}
	mock.lockEditPhoto.Lock()
	mock.calls.EditPhoto = append(mock.calls.EditPhoto, callInfo)
	mock.lockEditPhoto.Unlock()
	if mock.EditPhotoFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.EditPhotoFunc(context1, n, n1, s, s1, inlineKeyboardMarkup)
}

// EditPhotoCalls gets all the calls that were made to EditPhoto.
// Check the length with:
//
//	len(mockedpublisher.EditPhotoCalls())
func (mock *MoqPublisher) EditPhotoCalls() []struct {
	Context1             context.Context
	N                    int64
	N1                   int
	S                    string
	S1                   string
	InlineKeyboardMarkup *models.InlineKeyboardMarkup
} {
	var calls []struct {
		Context1             context.Context
		N                    int64
		N1                   int
		S                    string
		S1                   string
		InlineKeyboardMarkup *models.InlineKeyboardMarkup
	}
	mock.lockEditPhoto.RLock()
	calls = mock.calls.EditPhoto
	mock.lockEditPhoto.RUnlock()
	return calls
}

// SendPhoto calls SendPhotoFunc.
func (mock *MoqPublisher) SendPhoto(context1 context.Context, n int64, s string, s1 string, inlineKeyboardMarkup *models.InlineKeyboardMarkup) (int, error) {
	callInfo := struct {
		Context1             context.Context
		N                    int64
		S                    string
		S1                   string
		InlineKeyboardMarkup *models.InlineKeyboardMarkup
	}{
		Context1:             context1,
		N:                    n,
		S:                    s,
		S1:                   s1,
		InlineKeyboardMarkup: inlineKeyboardMarkup,
	}
	mock.lockSendPhoto.Lock()
	mock.calls.SendPhoto = append(mock.calls.SendPhoto, callInfo)
	mock.lockSendPhoto.Unlock()
	if mock.SendPhotoFunc == nil {
		var (
			n1  int
			err error
		)
		return n1, err
	}
	return mock.SendPhotoFunc(context1, n, s, s1, inlineKeyboardMarkup)
}

// SendPhotoCalls gets all the calls that were made to SendPhoto.
// Check the length with:
//
//	len(mockedpublisher.SendPhotoCalls())
func (mock *MoqPublisher) SendPhotoCalls() []struct {
	Context1             context.Context
	N                    int64
	S                    string
	S1                   string
	InlineKeyboardMarkup *models.InlineKeyboardMarkup
} {
	var calls []struct {
		Context1             context.Context
		N                    int64
		S                    string
		S1                   string
		InlineKeyboardMarkup *models.InlineKeyboardMarkup
	}
	mock.lockSendPhoto.RLock()
	calls = mock.calls.SendPhoto
	mock.lockSendPhoto.RUnlock()
	return calls
}

// SendText calls SendTextFunc.
func (mock *MoqPublisher) SendText(context1 context.Context, n int64, s string) (int, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		S        string
	}{
		Context1: context1,
		N:        n,
		S:        s,
	}
	mock.lockSendText.Lock()
	mock.calls.SendText = append(mock.calls.SendText, callInfo)
	mock.lockSendText.Unlock()
	if mock.SendTextFunc == nil {
		var (
			n1  int
			err error
		)
		return n1, err
	}
	return mock.SendTextFunc(context1, n, s)
}

// SendTextCalls gets all the calls that were made to SendText.
// Check the length with:
//
//	len(mockedpublisher.SendTextCalls())
func (mock *MoqPublisher) SendTextCalls() []struct {
	Context1 context.Context
	N        int64
	S        string
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		S        string
	}
	mock.lockSendText.RLock()
	calls = mock.calls.SendText
	mock.lockSendText.RUnlock()
	return calls
}
