// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package vote

import (
	"context"
	"sync"
	"time"

	"github.com/TiraelSedai/PhotoChallengeBot/internal/repository"
)

// Ensure that MoqVoteStore does implement voteStore.
// If this is not the case, regenerate this file with mockery.
var _ voteStore = &MoqVoteStore{}

// MoqVoteStore is a mock implementation of voteStore.
//
//	func TestSomethingThatUsesvoteStore(t *testing.T) {
//
//		// make and configure a mocked voteStore
//		mockedvoteStore := &MoqVoteStore{
//			AddManualVoteFunc: func(context1 context.Context, n int64, n1 int64, n2 int64, time1 time.Time) (repository.Vote, error) {
//				panic("mock out the AddManualVote method")
//			},
//			CreateVoteOrderFunc: func(context1 context.Context, n int64, n1 int64, int64s []int64) ([]repository.VoteOrderItem, error) {
//				panic("mock out the CreateVoteOrder method")
//			},
//			EnsureSelfVotesFunc: func(context1 context.Context, n int64, photos []repository.Photo, time1 time.Time) error {
//				panic("mock out the EnsureSelfVotes method")
//			},
//			GetProgressFunc: func(context1 context.Context, n int64, n1 int64) (*repository.VoteProgress, error) {
//				panic("mock out the GetProgress method")
//			},
//			ListVoteOrderFunc: func(context1 context.Context, n int64, n1 int64) ([]repository.VoteOrderItem, error) {
//				panic("mock out the ListVoteOrder method")
//			},
//			ManualVoteExistsFunc: func(context1 context.Context, n int64, n1 int64, n2 int64) (bool, error) {
//				panic("mock out the ManualVoteExists method")
//			},
//			RemoveManualVoteFunc: func(context1 context.Context, n int64, n1 int64, n2 int64) (bool, error) {
//				panic("mock out the RemoveManualVote method")
//			},
//			UpsertProgressFunc: func(context1 context.Context, voteProgress repository.VoteProgress) (repository.VoteProgress, error) {
//				panic("mock out the UpsertProgress method")
//			},
//		}
//
//		// use mockedvoteStore in code that requires voteStore
//		// and then make assertions.
//
//	}
type MoqVoteStore struct {
	// AddManualVoteFunc mocks the AddManualVote method.
	AddManualVoteFunc func(context1 context.Context, n int64, n1 int64, n2 int64, time1 time.Time) (repository.Vote, error)

	// CreateVoteOrderFunc mocks the CreateVoteOrder method.
	CreateVoteOrderFunc func(context1 context.Context, n int64, n1 int64, int64s []int64) ([]repository.VoteOrderItem, error)

	// EnsureSelfVotesFunc mocks the EnsureSelfVotes method.
	EnsureSelfVotesFunc func(context1 context.Context, n int64, photos []repository.Photo, time1 time.Time) error

	// GetProgressFunc mocks the GetProgress method.
	GetProgressFunc func(context1 context.Context, n int64, n1 int64) (*repository.VoteProgress, error)

	// ListVoteOrderFunc mocks the ListVoteOrder method.
	ListVoteOrderFunc func(context1 context.Context, n int64, n1 int64) ([]repository.VoteOrderItem, error)

	// ManualVoteExistsFunc mocks the ManualVoteExists method.
	ManualVoteExistsFunc func(context1 context.Context, n int64, n1 int64, n2 int64) (bool, error)

	// RemoveManualVoteFunc mocks the RemoveManualVote method.
	RemoveManualVoteFunc func(context1 context.Context, n int64, n1 int64, n2 int64) (bool, error)

	// UpsertProgressFunc mocks the UpsertProgress method.
	UpsertProgressFunc func(context1 context.Context, voteProgress repository.VoteProgress) (repository.VoteProgress, error)

	// calls tracks calls to the methods.
	calls struct {
		// AddManualVote holds details about calls to the AddManualVote method.
		AddManualVote []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// N1 is the n1 argument value.
			N1 int64
			// N2 is the n2 argument value.
			N2 int64
			// Time1 is the time1 argument value.
			Time1 time.Time
		}
		// CreateVoteOrder holds details about calls to the CreateVoteOrder method.
		CreateVoteOrder []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// N1 is the n1 argument value.
			N1 int64
			// Int64s is the int64s argument value.
			Int64s []int64
		}
		// EnsureSelfVotes holds details about calls to the EnsureSelfVotes method.
		EnsureSelfVotes []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// Photos is the photos argument value.
			Photos []repository.Photo
			// Time1 is the time1 argument value.
			Time1 time.Time
		}
		// GetProgress holds details about calls to the GetProgress method.
		GetProgress []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// N1 is the n1 argument value.
			N1 int64
		}
		// ListVoteOrder holds details about calls to the ListVoteOrder method.
		ListVoteOrder []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// N1 is the n1 argument value.
			N1 int64
		}
		// ManualVoteExists holds details about calls to the ManualVoteExists method.
		ManualVoteExists []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// N1 is the n1 argument value.
			N1 int64
			// N2 is the n2 argument value.
			N2 int64
		}
		// RemoveManualVote holds details about calls to the RemoveManualVote method.
		RemoveManualVote []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// N1 is the n1 argument value.
			N1 int64
			// N2 is the n2 argument value.
			N2 int64
		}
		// UpsertProgress holds details about calls to the UpsertProgress method.
		UpsertProgress []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// VoteProgress is the voteProgress argument value.
			VoteProgress repository.VoteProgress
		}
	}
	lockAddManualVote    sync.RWMutex
	lockCreateVoteOrder  sync.RWMutex
	lockEnsureSelfVotes  sync.RWMutex
	lockGetProgress      sync.RWMutex
	lockListVoteOrder    sync.RWMutex
	lockManualVoteExists sync.RWMutex
	lockRemoveManualVote sync.RWMutex
	lockUpsertProgress   sync.RWMutex
}

// AddManualVote calls AddManualVoteFunc.
func (mock *MoqVoteStore) AddManualVote(context1 context.Context, n int64, n1 int64, n2 int64, time1 time.Time) (repository.Vote, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		N1       int64
		N2       int64
		Time1    time.Time
	}{
		Context1: context1,
		N:        n,
		N1:       n1,
		N2:       n2,
		Time1:    time1,
	}
	mock.lockAddManualVote.Lock()
	mock.calls.AddManualVote = append(mock.calls.AddManualVote, callInfo)
	mock.lockAddManualVote.Unlock()
	if mock.AddManualVoteFunc == nil {
		var (
			vote repository.Vote
			err  error
		)
		return vote, err
	}
	return mock.AddManualVoteFunc(context1, n, n1, n2, time1)
}

// AddManualVoteCalls gets all the calls that were made to AddManualVote.
// Check the length with:
//
//	len(mockedvoteStore.AddManualVoteCalls())
func (mock *MoqVoteStore) AddManualVoteCalls() []struct {
	Context1 context.Context
	N        int64
	N1       int64
	N2       int64
	Time1    time.Time
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		N1       int64
		N2       int64
		Time1    time.Time
	}
	mock.lockAddManualVote.RLock()
	calls = mock.calls.AddManualVote
	mock.lockAddManualVote.RUnlock()
	return calls
}

// CreateVoteOrder calls CreateVoteOrderFunc.
func (mock *MoqVoteStore) CreateVoteOrder(context1 context.Context, n int64, n1 int64, int64s []int64) ([]repository.VoteOrderItem, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		N1       int64
		Int64s   []int64
	}{
		Context1: context1,
		N:        n,
		N1:       n1,
		Int64s:   int64s,
	}
	mock.lockCreateVoteOrder.Lock()
	mock.calls.CreateVoteOrder = append(mock.calls.CreateVoteOrder, callInfo)
	mock.lockCreateVoteOrder.Unlock()
	if mock.CreateVoteOrderFunc == nil {
		var (
			voteOrderItems []repository.VoteOrderItem
			err            error
		)
		return voteOrderItems, err
	}
	return mock.CreateVoteOrderFunc(context1, n, n1, int64s)
}

// CreateVoteOrderCalls gets all the calls that were made to CreateVoteOrder.
// Check the length with:
//
//	len(mockedvoteStore.CreateVoteOrderCalls())
func (mock *MoqVoteStore) CreateVoteOrderCalls() []struct {
	Context1 context.Context
	N        int64
	N1       int64
	Int64s   []int64
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		N1       int64
		Int64s   []int64
	}
	mock.lockCreateVoteOrder.RLock()
	calls = mock.calls.CreateVoteOrder
	mock.lockCreateVoteOrder.RUnlock()
	return calls
}

// EnsureSelfVotes calls EnsureSelfVotesFunc.
func (mock *MoqVoteStore) EnsureSelfVotes(context1 context.Context, n int64, photos []repository.Photo, time1 time.Time) error {
	callInfo := struct {
		Context1 context.Context
		N        int64
		Photos   []repository.Photo
		Time1    time.Time
	}{
		Context1: context1,
		N:        n,
		Photos:   photos,
		Time1:    time1,
	}
	mock.lockEnsureSelfVotes.Lock()
	mock.calls.EnsureSelfVotes = append(mock.calls.EnsureSelfVotes, callInfo)
	mock.lockEnsureSelfVotes.Unlock()
	if mock.EnsureSelfVotesFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.EnsureSelfVotesFunc(context1, n, photos, time1)
}

// EnsureSelfVotesCalls gets all the calls that were made to EnsureSelfVotes.
// Check the length with:
//
//	len(mockedvoteStore.EnsureSelfVotesCalls())
func (mock *MoqVoteStore) EnsureSelfVotesCalls() []struct {
	Context1 context.Context
	N        int64
	Photos   []repository.Photo
	Time1    time.Time
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		Photos   []repository.Photo
		Time1    time.Time
	}
	mock.lockEnsureSelfVotes.RLock()
	calls = mock.calls.EnsureSelfVotes
	mock.lockEnsureSelfVotes.RUnlock()
	return calls
}

// GetProgress calls GetProgressFunc.
func (mock *MoqVoteStore) GetProgress(context1 context.Context, n int64, n1 int64) (*repository.VoteProgress, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		N1       int64
	}{
		Context1: context1,
		N:        n,
		N1:       n1,
	}
	mock.lockGetProgress.Lock()
	mock.calls.GetProgress = append(mock.calls.GetProgress, callInfo)
	mock.lockGetProgress.Unlock()
	if mock.GetProgressFunc == nil {
		var (
			voteProgress *repository.VoteProgress
			err          error
		)
		return voteProgress, err
	}
	return mock.GetProgressFunc(context1, n, n1)
}

// GetProgressCalls gets all the calls that were made to GetProgress.
// Check the length with:
//
//	len(mockedvoteStore.GetProgressCalls())
func (mock *MoqVoteStore) GetProgressCalls() []struct {
	Context1 context.Context
	N        int64
	N1       int64
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		N1       int64
	}
	mock.lockGetProgress.RLock()
	calls = mock.calls.GetProgress
	mock.lockGetProgress.RUnlock()
	return calls
}

// ListVoteOrder calls ListVoteOrderFunc.
func (mock *MoqVoteStore) ListVoteOrder(context1 context.Context, n int64, n1 int64) ([]repository.VoteOrderItem, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		N1       int64
	}{
		Context1: context1,
		N:        n,
		N1:       n1,
	}
	mock.lockListVoteOrder.Lock()
	mock.calls.ListVoteOrder = append(mock.calls.ListVoteOrder, callInfo)
	mock.lockListVoteOrder.Unlock()
	if mock.ListVoteOrderFunc == nil {
		var (
			voteOrderItems []repository.VoteOrderItem
			err            error
		)
		return voteOrderItems, err
	}
	return mock.ListVoteOrderFunc(context1, n, n1)
}

// ListVoteOrderCalls gets all the calls that were made to ListVoteOrder.
// Check the length with:
//
//	len(mockedvoteStore.ListVoteOrderCalls())
func (mock *MoqVoteStore) ListVoteOrderCalls() []struct {
	Context1 context.Context
	N        int64
	N1       int64
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		N1       int64
	}
	mock.lockListVoteOrder.RLock()
	calls = mock.calls.ListVoteOrder
	mock.lockListVoteOrder.RUnlock()
	return calls
}

// ManualVoteExists calls ManualVoteExistsFunc.
func (mock *MoqVoteStore) ManualVoteExists(context1 context.Context, n int64, n1 int64, n2 int64) (bool, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		N1       int64
		N2       int64
	}{
		Context1: context1,
		N:        n,
		N1:       n1,
		N2:       n2,
	}
	mock.lockManualVoteExists.Lock()
	mock.calls.ManualVoteExists = append(mock.calls.ManualVoteExists, callInfo)
	mock.lockManualVoteExists.Unlock()
	if mock.ManualVoteExistsFunc == nil {
		var (
			b   bool
			err error
		)
		return b, err
	}
	return mock.ManualVoteExistsFunc(context1, n, n1, n2)
}

// ManualVoteExistsCalls gets all the calls that were made to ManualVoteExists.
// Check the length with:
//
//	len(mockedvoteStore.ManualVoteExistsCalls())
func (mock *MoqVoteStore) ManualVoteExistsCalls() []struct {
	Context1 context.Context
	N        int64
	N1       int64
	N2       int64
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		N1       int64
		N2       int64
	}
	mock.lockManualVoteExists.RLock()
	calls = mock.calls.ManualVoteExists
	mock.lockManualVoteExists.RUnlock()
	return calls
}

// RemoveManualVote calls RemoveManualVoteFunc.
func (mock *MoqVoteStore) RemoveManualVote(context1 context.Context, n int64, n1 int64, n2 int64) (bool, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		N1       int64
		N2       int64
	}{
		Context1: context1,
		N:        n,
		N1:       n1,
		N2:       n2,
	}
	mock.lockRemoveManualVote.Lock()
	mock.calls.RemoveManualVote = append(mock.calls.RemoveManualVote, callInfo)
	mock.lockRemoveManualVote.Unlock()
	if mock.RemoveManualVoteFunc == nil {
		var (
			b   bool
			err error
		)
		return b, err
	}
	return mock.RemoveManualVoteFunc(context1, n, n1, n2)
}

// RemoveManualVoteCalls gets all the calls that were made to RemoveManualVote.
// Check the length with:
//
//	len(mockedvoteStore.RemoveManualVoteCalls())
func (mock *MoqVoteStore) RemoveManualVoteCalls() []struct {
	Context1 context.Context
	N        int64
	N1       int64
	N2       int64
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		N1       int64
		N2       int64
	}
	mock.lockRemoveManualVote.RLock()
	calls = mock.calls.RemoveManualVote
	mock.lockRemoveManualVote.RUnlock()
	return calls
}

// UpsertProgress calls UpsertProgressFunc.
func (mock *MoqVoteStore) UpsertProgress(context1 context.Context, voteProgress repository.VoteProgress) (repository.VoteProgress, error) {
	callInfo := struct {
		Context1     context.Context
		VoteProgress repository.VoteProgress
	}{
		Context1:     context1,
		VoteProgress: voteProgress,
	}
	mock.lockUpsertProgress.Lock()
	mock.calls.UpsertProgress = append(mock.calls.UpsertProgress, callInfo)
	mock.lockUpsertProgress.Unlock()
	if mock.UpsertProgressFunc == nil {
		var (
			voteProgress1 repository.VoteProgress
			err           error
		)
		return voteProgress1, err
	}
	return mock.UpsertProgressFunc(context1, voteProgress)
}

// UpsertProgressCalls gets all the calls that were made to UpsertProgress.
// Check the length with:
//
//	len(mockedvoteStore.UpsertProgressCalls())
func (mock *MoqVoteStore) UpsertProgressCalls() []struct {
	Context1     context.Context
	VoteProgress repository.VoteProgress
} {
	var calls []struct {
		Context1     context.Context
		VoteProgress repository.VoteProgress
	}
	mock.lockUpsertProgress.RLock()
	calls = mock.calls.UpsertProgress
	mock.lockUpsertProgress.RUnlock()
	return calls
}
