// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package photo

import (
	"context"
	"sync"

	"github.com/TiraelSedai/PhotoChallengeBot/internal/repository"
)

// Ensure that MoqPhotos does implement photos.
// If this is not the case, regenerate this file with mockery.
var _ photos = &MoqPhotos{}

// MoqPhotos is a mock implementation of photos.
//
//	func TestSomethingThatUsesphotos(t *testing.T) {
//
//		// make and configure a mocked photos
//		mockedphotos := &MoqPhotos{
//			UpsertCurrentFunc: func(context1 context.Context, upsertPhotoInput repository.UpsertPhotoInput) (repository.Photo, bool, error) {
//				panic("mock out the UpsertCurrent method")
//			},
//		}
//
//		// use mockedphotos in code that requires photos
//		// and then make assertions.
//
//	}
type MoqPhotos struct {
	// UpsertCurrentFunc mocks the UpsertCurrent method.
	UpsertCurrentFunc func(context1 context.Context, upsertPhotoInput repository.UpsertPhotoInput) (repository.Photo, bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// UpsertCurrent holds details about calls to the UpsertCurrent method.
		UpsertCurrent []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// UpsertPhotoInput is the upsertPhotoInput argument value.
			UpsertPhotoInput repository.UpsertPhotoInput
		}
	}
	lockUpsertCurrent sync.RWMutex
}

// UpsertCurrent calls UpsertCurrentFunc.
func (mock *MoqPhotos) UpsertCurrent(context1 context.Context, upsertPhotoInput repository.UpsertPhotoInput) (repository.Photo, bool, error) {
	callInfo := struct {
		Context1         context.Context
		UpsertPhotoInput repository.UpsertPhotoInput
	}{
		Context1:         context1,
		UpsertPhotoInput: upsertPhotoInput,
	}
	mock.lockUpsertCurrent.Lock()
	mock.calls.UpsertCurrent = append(mock.calls.UpsertCurrent, callInfo)
	mock.lockUpsertCurrent.Unlock()
	if mock.UpsertCurrentFunc == nil {
		var (
			photo repository.Photo
			b     bool
			err   error
		)
		return photo, b, err
	}
	return mock.UpsertCurrentFunc(context1, upsertPhotoInput)
}

// UpsertCurrentCalls gets all the calls that were made to UpsertCurrent.
// Check the length with:
//
//	len(mockedphotos.UpsertCurrentCalls())
func (mock *MoqPhotos) UpsertCurrentCalls() []struct {
	Context1         context.Context
	UpsertPhotoInput repository.UpsertPhotoInput
} {
	var calls []struct {
		Context1         context.Context
		UpsertPhotoInput repository.UpsertPhotoInput
	}
	mock.lockUpsertCurrent.RLock()
	calls = mock.calls.UpsertCurrent
	mock.lockUpsertCurrent.RUnlock()
	return calls
}
