// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package photo

import (
	"context"
	"sync"
)

// Ensure that MoqPublisher does implement publisher.
// If this is not the case, regenerate this file with mockery.
var _ publisher = &MoqPublisher{}

// MoqPublisher is a mock implementation of publisher.
//
//	func TestSomethingThatUsespublisher(t *testing.T) {
//
//		// make and configure a mocked publisher
//		mockedpublisher := &MoqPublisher{
//			SendTextReplyFunc: func(context1 context.Context, n int64, s string, n1 int) (int, error) {
//				panic("mock out the SendTextReply method")
//			},
//		}
//
//		// use mockedpublisher in code that requires publisher
//		// and then make assertions.
//
//	}
type MoqPublisher struct {
	// SendTextReplyFunc mocks the SendTextReply method.
	SendTextReplyFunc func(context1 context.Context, n int64, s string, n1 int) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// SendTextReply holds details about calls to the SendTextReply method.
		SendTextReply []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// S is the s argument value.
			S string
			// N1 is the n1 argument value.
			N1 int
		}
	}
	lockSendTextReply sync.RWMutex
}

// SendTextReply calls SendTextReplyFunc.
func (mock *MoqPublisher) SendTextReply(context1 context.Context, n int64, s string, n1 int) (int, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		S        string
		N1       int
	}{
		Context1: context1,
		N:        n,
		S:        s,
		N1:       n1,
	}
	mock.lockSendTextReply.Lock()
	mock.calls.SendTextReply = append(mock.calls.SendTextReply, callInfo)
	mock.lockSendTextReply.Unlock()
	if mock.SendTextReplyFunc == nil {
		var (
			n2  int
			err error
		)
		return n2, err
	}
	return mock.SendTextReplyFunc(context1, n, s, n1)
}

// SendTextReplyCalls gets all the calls that were made to SendTextReply.
// Check the length with:
//
//	len(mockedpublisher.SendTextReplyCalls())
func (mock *MoqPublisher) SendTextReplyCalls() []struct {
	Context1 context.Context
	N        int64
	S        string
	N1       int
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		S        string
		N1       int
	}
	mock.lockSendTextReply.RLock()
	calls = mock.calls.SendTextReply
	mock.lockSendTextReply.RUnlock()
	return calls
}
