// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package admin

import (
	"sync"

	"github.com/TiraelSedai/PhotoChallengeBot/internal/templates"
)

// Ensure that MoqAnnouncementRenderer does implement announcementRenderer.
// If this is not the case, regenerate this file with mockery.
var _ announcementRenderer = &MoqAnnouncementRenderer{}

// MoqAnnouncementRenderer is a mock implementation of announcementRenderer.
//
//	func TestSomethingThatUsesannouncementRenderer(t *testing.T) {
//
//		// make and configure a mocked announcementRenderer
//		mockedannouncementRenderer := &MoqAnnouncementRenderer{
//			ChallengeAnnouncementFunc: func(challengeAnnouncementData templates.ChallengeAnnouncementData) (string, error) {
//				panic("mock out the ChallengeAnnouncement method")
//			},
//			CustomChallengeAnnouncementFunc: func(s string, s1 string) (string, error) {
//				panic("mock out the CustomChallengeAnnouncement method")
//			},
//		}
//
//		// use mockedannouncementRenderer in code that requires announcementRenderer
//		// and then make assertions.
//
//	}
type MoqAnnouncementRenderer struct {
	// ChallengeAnnouncementFunc mocks the ChallengeAnnouncement method.
	ChallengeAnnouncementFunc func(challengeAnnouncementData templates.ChallengeAnnouncementData) (string, error)

	// CustomChallengeAnnouncementFunc mocks the CustomChallengeAnnouncement method.
	CustomChallengeAnnouncementFunc func(s string, s1 string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// ChallengeAnnouncement holds details about calls to the ChallengeAnnouncement method.
		ChallengeAnnouncement []struct {
			// ChallengeAnnouncementData is the challengeAnnouncementData argument value.
			ChallengeAnnouncementData templates.ChallengeAnnouncementData
		}
		// CustomChallengeAnnouncement holds details about calls to the CustomChallengeAnnouncement method.
		CustomChallengeAnnouncement []struct {
			// S is the s argument value.
			S string
			// S1 is the s1 argument value.
			S1 string
		}
	}
	lockChallengeAnnouncement       sync.RWMutex
	lockCustomChallengeAnnouncement sync.RWMutex
}

// ChallengeAnnouncement calls ChallengeAnnouncementFunc.
func (mock *MoqAnnouncementRenderer) ChallengeAnnouncement(challengeAnnouncementData templates.ChallengeAnnouncementData) (string, error) {
	callInfo := struct {
		ChallengeAnnouncementData templates.ChallengeAnnouncementData
	}{
		ChallengeAnnouncementData: challengeAnnouncementData,
	}
	mock.lockChallengeAnnouncement.Lock()
	mock.calls.ChallengeAnnouncement = append(mock.calls.ChallengeAnnouncement, callInfo)
	mock.lockChallengeAnnouncement.Unlock()
	if mock.ChallengeAnnouncementFunc == nil {
		var (
			s   string
			err error
		)
		return s, err
	}
	return mock.ChallengeAnnouncementFunc(challengeAnnouncementData)
}

// ChallengeAnnouncementCalls gets all the calls that were made to ChallengeAnnouncement.
// Check the length with:
//
//	len(mockedannouncementRenderer.ChallengeAnnouncementCalls())
func (mock *MoqAnnouncementRenderer) ChallengeAnnouncementCalls() []struct {
	ChallengeAnnouncementData templates.ChallengeAnnouncementData
} {
	var calls []struct {
		ChallengeAnnouncementData templates.ChallengeAnnouncementData
	}
	mock.lockChallengeAnnouncement.RLock()
	calls = mock.calls.ChallengeAnnouncement
	mock.lockChallengeAnnouncement.RUnlock()
	return calls
}

// CustomChallengeAnnouncement calls CustomChallengeAnnouncementFunc.
func (mock *MoqAnnouncementRenderer) CustomChallengeAnnouncement(s string, s1 string) (string, error) {
	callInfo := struct {
		S  string
		S1 string
	}{
		S:  s,
		S1: s1,
	}
	mock.lockCustomChallengeAnnouncement.Lock()
	mock.calls.CustomChallengeAnnouncement = append(mock.calls.CustomChallengeAnnouncement, callInfo)
	mock.lockCustomChallengeAnnouncement.Unlock()
	if mock.CustomChallengeAnnouncementFunc == nil {
		var (
			s2  string
			err error
		)
		return s2, err
	}
	return mock.CustomChallengeAnnouncementFunc(s, s1)
}

// CustomChallengeAnnouncementCalls gets all the calls that were made to CustomChallengeAnnouncement.
// Check the length with:
//
//	len(mockedannouncementRenderer.CustomChallengeAnnouncementCalls())
func (mock *MoqAnnouncementRenderer) CustomChallengeAnnouncementCalls() []struct {
	S  string
	S1 string
} {
	var calls []struct {
		S  string
		S1 string
	}
	mock.lockCustomChallengeAnnouncement.RLock()
	calls = mock.calls.CustomChallengeAnnouncement
	mock.lockCustomChallengeAnnouncement.RUnlock()
	return calls
}
