// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package admin

import (
	"sync"

	"github.com/TiraelSedai/PhotoChallengeBot/internal/templates"
)

// Ensure that MoqAnnouncementRenderer does implement announcementRenderer.
// If this is not the case, regenerate this file with mockery.
var _ announcementRenderer = &MoqAnnouncementRenderer{}

// MoqAnnouncementRenderer is a mock implementation of announcementRenderer.
//
//	func TestSomethingThatUsesannouncementRenderer(t *testing.T) {
//
//		// make and configure a mocked announcementRenderer
//		mockedannouncementRenderer := &MoqAnnouncementRenderer{
//			ChallengeAnnouncementFunc: func(challengeAnnouncementData templates.ChallengeAnnouncementData) (string, error) {
//				panic("mock out the ChallengeAnnouncement method")
//			},
//		}
//
//		// use mockedannouncementRenderer in code that requires announcementRenderer
//		// and then make assertions.
//
//	}
type MoqAnnouncementRenderer struct {
	// ChallengeAnnouncementFunc mocks the ChallengeAnnouncement method.
	ChallengeAnnouncementFunc func(challengeAnnouncementData templates.ChallengeAnnouncementData) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// ChallengeAnnouncement holds details about calls to the ChallengeAnnouncement method.
		ChallengeAnnouncement []struct {
			// ChallengeAnnouncementData is the challengeAnnouncementData argument value.
			ChallengeAnnouncementData templates.ChallengeAnnouncementData
		}
	}
	lockChallengeAnnouncement sync.RWMutex
}

// ChallengeAnnouncement calls ChallengeAnnouncementFunc.
func (mock *MoqAnnouncementRenderer) ChallengeAnnouncement(challengeAnnouncementData templates.ChallengeAnnouncementData) (string, error) {
	callInfo := struct {
		ChallengeAnnouncementData templates.ChallengeAnnouncementData
	}{
		ChallengeAnnouncementData: challengeAnnouncementData,
	}
	mock.lockChallengeAnnouncement.Lock()
	mock.calls.ChallengeAnnouncement = append(mock.calls.ChallengeAnnouncement, callInfo)
	mock.lockChallengeAnnouncement.Unlock()
	if mock.ChallengeAnnouncementFunc == nil {
		var (
			s   string
			err error
		)
		return s, err
	}
	return mock.ChallengeAnnouncementFunc(challengeAnnouncementData)
}

// ChallengeAnnouncementCalls gets all the calls that were made to ChallengeAnnouncement.
// Check the length with:
//
//	len(mockedannouncementRenderer.ChallengeAnnouncementCalls())
func (mock *MoqAnnouncementRenderer) ChallengeAnnouncementCalls() []struct {
	ChallengeAnnouncementData templates.ChallengeAnnouncementData
} {
	var calls []struct {
		ChallengeAnnouncementData templates.ChallengeAnnouncementData
	}
	mock.lockChallengeAnnouncement.RLock()
	calls = mock.calls.ChallengeAnnouncement
	mock.lockChallengeAnnouncement.RUnlock()
	return calls
}
