// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package admin

import (
	"context"
	"sync"
	"time"

	"github.com/TiraelSedai/PhotoChallengeBot/internal/repository"
)

// Ensure that MoqChallengeAnnouncements does implement challengeAnnouncements.
// If this is not the case, regenerate this file with mockery.
var _ challengeAnnouncements = &MoqChallengeAnnouncements{}

// MoqChallengeAnnouncements is a mock implementation of challengeAnnouncements.
//
//	func TestSomethingThatUseschallengeAnnouncements(t *testing.T) {
//
//		// make and configure a mocked challengeAnnouncements
//		mockedchallengeAnnouncements := &MoqChallengeAnnouncements{
//			FindLatestWithResultsFunc: func(context1 context.Context, n int64) (*repository.Challenge, error) {
//				panic("mock out the FindLatestWithResults method")
//			},
//			GetFunc: func(context1 context.Context, n int64) (repository.Challenge, error) {
//				panic("mock out the Get method")
//			},
//			SetAnnouncementMessageIDFunc: func(context1 context.Context, n int64, n1 int, time1 time.Time) error {
//				panic("mock out the SetAnnouncementMessageID method")
//			},
//		}
//
//		// use mockedchallengeAnnouncements in code that requires challengeAnnouncements
//		// and then make assertions.
//
//	}
type MoqChallengeAnnouncements struct {
	// FindLatestWithResultsFunc mocks the FindLatestWithResults method.
	FindLatestWithResultsFunc func(context1 context.Context, n int64) (*repository.Challenge, error)

	// GetFunc mocks the Get method.
	GetFunc func(context1 context.Context, n int64) (repository.Challenge, error)

	// SetAnnouncementMessageIDFunc mocks the SetAnnouncementMessageID method.
	SetAnnouncementMessageIDFunc func(context1 context.Context, n int64, n1 int, time1 time.Time) error

	// calls tracks calls to the methods.
	calls struct {
		// FindLatestWithResults holds details about calls to the FindLatestWithResults method.
		FindLatestWithResults []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
		}
		// SetAnnouncementMessageID holds details about calls to the SetAnnouncementMessageID method.
		SetAnnouncementMessageID []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// N1 is the n1 argument value.
			N1 int
			// Time1 is the time1 argument value.
			Time1 time.Time
		}
	}
	lockFindLatestWithResults    sync.RWMutex
	lockGet                      sync.RWMutex
	lockSetAnnouncementMessageID sync.RWMutex
}

// FindLatestWithResults calls FindLatestWithResultsFunc.
func (mock *MoqChallengeAnnouncements) FindLatestWithResults(context1 context.Context, n int64) (*repository.Challenge, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
	}{
		Context1: context1,
		N:        n,
	}
	mock.lockFindLatestWithResults.Lock()
	mock.calls.FindLatestWithResults = append(mock.calls.FindLatestWithResults, callInfo)
	mock.lockFindLatestWithResults.Unlock()
	if mock.FindLatestWithResultsFunc == nil {
		var (
			challenge *repository.Challenge
			err       error
		)
		return challenge, err
	}
	return mock.FindLatestWithResultsFunc(context1, n)
}

// FindLatestWithResultsCalls gets all the calls that were made to FindLatestWithResults.
// Check the length with:
//
//	len(mockedchallengeAnnouncements.FindLatestWithResultsCalls())
func (mock *MoqChallengeAnnouncements) FindLatestWithResultsCalls() []struct {
	Context1 context.Context
	N        int64
} {
	var calls []struct {
		Context1 context.Context
		N        int64
	}
	mock.lockFindLatestWithResults.RLock()
	calls = mock.calls.FindLatestWithResults
	mock.lockFindLatestWithResults.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *MoqChallengeAnnouncements) Get(context1 context.Context, n int64) (repository.Challenge, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
	}{
		Context1: context1,
		N:        n,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			challenge repository.Challenge
			err       error
		)
		return challenge, err
	}
	return mock.GetFunc(context1, n)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedchallengeAnnouncements.GetCalls())
func (mock *MoqChallengeAnnouncements) GetCalls() []struct {
	Context1 context.Context
	N        int64
} {
	var calls []struct {
		Context1 context.Context
		N        int64
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// SetAnnouncementMessageID calls SetAnnouncementMessageIDFunc.
func (mock *MoqChallengeAnnouncements) SetAnnouncementMessageID(context1 context.Context, n int64, n1 int, time1 time.Time) error {
	callInfo := struct {
		Context1 context.Context
		N        int64
		N1       int
		Time1    time.Time
	}{
		Context1: context1,
		N:        n,
		N1:       n1,
		Time1:    time1,
	}
	mock.lockSetAnnouncementMessageID.Lock()
	mock.calls.SetAnnouncementMessageID = append(mock.calls.SetAnnouncementMessageID, callInfo)
	mock.lockSetAnnouncementMessageID.Unlock()
	if mock.SetAnnouncementMessageIDFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.SetAnnouncementMessageIDFunc(context1, n, n1, time1)
}

// SetAnnouncementMessageIDCalls gets all the calls that were made to SetAnnouncementMessageID.
// Check the length with:
//
//	len(mockedchallengeAnnouncements.SetAnnouncementMessageIDCalls())
func (mock *MoqChallengeAnnouncements) SetAnnouncementMessageIDCalls() []struct {
	Context1 context.Context
	N        int64
	N1       int
	Time1    time.Time
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		N1       int
		Time1    time.Time
	}
	mock.lockSetAnnouncementMessageID.RLock()
	calls = mock.calls.SetAnnouncementMessageID
	mock.lockSetAnnouncementMessageID.RUnlock()
	return calls
}
