// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package admin

import (
	"context"
	"sync"

	"github.com/TiraelSedai/PhotoChallengeBot/internal/challenge"
	"github.com/TiraelSedai/PhotoChallengeBot/internal/repository"
)

// Ensure that MoqChallengePlanner does implement challengePlanner.
// If this is not the case, regenerate this file with mockery.
var _ challengePlanner = &MoqChallengePlanner{}

// MoqChallengePlanner is a mock implementation of challengePlanner.
//
//	func TestSomethingThatUseschallengePlanner(t *testing.T) {
//
//		// make and configure a mocked challengePlanner
//		mockedchallengePlanner := &MoqChallengePlanner{
//			CreateActiveFunc: func(context1 context.Context, createInput challenge.CreateInput) (repository.Challenge, error) {
//				panic("mock out the CreateActive method")
//			},
//			CreatePlannedFunc: func(context1 context.Context, plan challenge.Plan) (repository.Challenge, error) {
//				panic("mock out the CreatePlanned method")
//			},
//			PlanFunc: func(context1 context.Context, createInput challenge.CreateInput) (challenge.Plan, error) {
//				panic("mock out the Plan method")
//			},
//		}
//
//		// use mockedchallengePlanner in code that requires challengePlanner
//		// and then make assertions.
//
//	}
type MoqChallengePlanner struct {
	// CreateActiveFunc mocks the CreateActive method.
	CreateActiveFunc func(context1 context.Context, createInput challenge.CreateInput) (repository.Challenge, error)

	// CreatePlannedFunc mocks the CreatePlanned method.
	CreatePlannedFunc func(context1 context.Context, plan challenge.Plan) (repository.Challenge, error)

	// PlanFunc mocks the Plan method.
	PlanFunc func(context1 context.Context, createInput challenge.CreateInput) (challenge.Plan, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateActive holds details about calls to the CreateActive method.
		CreateActive []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// CreateInput is the createInput argument value.
			CreateInput challenge.CreateInput
		}
		// CreatePlanned holds details about calls to the CreatePlanned method.
		CreatePlanned []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// Plan is the plan argument value.
			Plan challenge.Plan
		}
		// Plan holds details about calls to the Plan method.
		Plan []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// CreateInput is the createInput argument value.
			CreateInput challenge.CreateInput
		}
	}
	lockCreateActive  sync.RWMutex
	lockCreatePlanned sync.RWMutex
	lockPlan          sync.RWMutex
}

// CreateActive calls CreateActiveFunc.
func (mock *MoqChallengePlanner) CreateActive(context1 context.Context, createInput challenge.CreateInput) (repository.Challenge, error) {
	callInfo := struct {
		Context1    context.Context
		CreateInput challenge.CreateInput
	}{
		Context1:    context1,
		CreateInput: createInput,
	}
	mock.lockCreateActive.Lock()
	mock.calls.CreateActive = append(mock.calls.CreateActive, callInfo)
	mock.lockCreateActive.Unlock()
	if mock.CreateActiveFunc == nil {
		var (
			challenge1 repository.Challenge
			err        error
		)
		return challenge1, err
	}
	return mock.CreateActiveFunc(context1, createInput)
}

// CreateActiveCalls gets all the calls that were made to CreateActive.
// Check the length with:
//
//	len(mockedchallengePlanner.CreateActiveCalls())
func (mock *MoqChallengePlanner) CreateActiveCalls() []struct {
	Context1    context.Context
	CreateInput challenge.CreateInput
} {
	var calls []struct {
		Context1    context.Context
		CreateInput challenge.CreateInput
	}
	mock.lockCreateActive.RLock()
	calls = mock.calls.CreateActive
	mock.lockCreateActive.RUnlock()
	return calls
}

// CreatePlanned calls CreatePlannedFunc.
func (mock *MoqChallengePlanner) CreatePlanned(context1 context.Context, plan challenge.Plan) (repository.Challenge, error) {
	callInfo := struct {
		Context1 context.Context
		Plan     challenge.Plan
	}{
		Context1: context1,
		Plan:     plan,
	}
	mock.lockCreatePlanned.Lock()
	mock.calls.CreatePlanned = append(mock.calls.CreatePlanned, callInfo)
	mock.lockCreatePlanned.Unlock()
	if mock.CreatePlannedFunc == nil {
		var (
			challenge1 repository.Challenge
			err        error
		)
		return challenge1, err
	}
	return mock.CreatePlannedFunc(context1, plan)
}

// CreatePlannedCalls gets all the calls that were made to CreatePlanned.
// Check the length with:
//
//	len(mockedchallengePlanner.CreatePlannedCalls())
func (mock *MoqChallengePlanner) CreatePlannedCalls() []struct {
	Context1 context.Context
	Plan     challenge.Plan
} {
	var calls []struct {
		Context1 context.Context
		Plan     challenge.Plan
	}
	mock.lockCreatePlanned.RLock()
	calls = mock.calls.CreatePlanned
	mock.lockCreatePlanned.RUnlock()
	return calls
}

// Plan calls PlanFunc.
func (mock *MoqChallengePlanner) Plan(context1 context.Context, createInput challenge.CreateInput) (challenge.Plan, error) {
	callInfo := struct {
		Context1    context.Context
		CreateInput challenge.CreateInput
	}{
		Context1:    context1,
		CreateInput: createInput,
	}
	mock.lockPlan.Lock()
	mock.calls.Plan = append(mock.calls.Plan, callInfo)
	mock.lockPlan.Unlock()
	if mock.PlanFunc == nil {
		var (
			plan challenge.Plan
			err  error
		)
		return plan, err
	}
	return mock.PlanFunc(context1, createInput)
}

// PlanCalls gets all the calls that were made to Plan.
// Check the length with:
//
//	len(mockedchallengePlanner.PlanCalls())
func (mock *MoqChallengePlanner) PlanCalls() []struct {
	Context1    context.Context
	CreateInput challenge.CreateInput
} {
	var calls []struct {
		Context1    context.Context
		CreateInput challenge.CreateInput
	}
	mock.lockPlan.RLock()
	calls = mock.calls.Plan
	mock.lockPlan.RUnlock()
	return calls
}
