// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package admin

import (
	"context"
	"sync"

	"github.com/go-telegram/bot/models"
)

// Ensure that MoqCreateChallengePublisher does implement createChallengePublisher.
// If this is not the case, regenerate this file with mockery.
var _ createChallengePublisher = &MoqCreateChallengePublisher{}

// MoqCreateChallengePublisher is a mock implementation of createChallengePublisher.
//
//	func TestSomethingThatUsescreateChallengePublisher(t *testing.T) {
//
//		// make and configure a mocked createChallengePublisher
//		mockedcreateChallengePublisher := &MoqCreateChallengePublisher{
//			PinFunc: func(context1 context.Context, n int64, n1 int) error {
//				panic("mock out the Pin method")
//			},
//			SendMarkdownFunc: func(context1 context.Context, n int64, s string) (int, error) {
//				panic("mock out the SendMarkdown method")
//			},
//			SendMarkdownPhotoFunc: func(context1 context.Context, n int64, s string, s1 string) (int, error) {
//				panic("mock out the SendMarkdownPhoto method")
//			},
//			SendPhotoFunc: func(context1 context.Context, n int64, s string, s1 string, inlineKeyboardMarkup *models.InlineKeyboardMarkup) (int, error) {
//				panic("mock out the SendPhoto method")
//			},
//			SendTextFunc: func(context1 context.Context, n int64, s string) (int, error) {
//				panic("mock out the SendText method")
//			},
//		}
//
//		// use mockedcreateChallengePublisher in code that requires createChallengePublisher
//		// and then make assertions.
//
//	}
type MoqCreateChallengePublisher struct {
	// PinFunc mocks the Pin method.
	PinFunc func(context1 context.Context, n int64, n1 int) error

	// SendMarkdownFunc mocks the SendMarkdown method.
	SendMarkdownFunc func(context1 context.Context, n int64, s string) (int, error)

	// SendMarkdownPhotoFunc mocks the SendMarkdownPhoto method.
	SendMarkdownPhotoFunc func(context1 context.Context, n int64, s string, s1 string) (int, error)

	// SendPhotoFunc mocks the SendPhoto method.
	SendPhotoFunc func(context1 context.Context, n int64, s string, s1 string, inlineKeyboardMarkup *models.InlineKeyboardMarkup) (int, error)

	// SendTextFunc mocks the SendText method.
	SendTextFunc func(context1 context.Context, n int64, s string) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// Pin holds details about calls to the Pin method.
		Pin []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// N1 is the n1 argument value.
			N1 int
		}
		// SendMarkdown holds details about calls to the SendMarkdown method.
		SendMarkdown []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// S is the s argument value.
			S string
		}
		// SendMarkdownPhoto holds details about calls to the SendMarkdownPhoto method.
		SendMarkdownPhoto []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// S is the s argument value.
			S string
			// S1 is the s1 argument value.
			S1 string
		}
		// SendPhoto holds details about calls to the SendPhoto method.
		SendPhoto []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// S is the s argument value.
			S string
			// S1 is the s1 argument value.
			S1 string
			// InlineKeyboardMarkup is the inlineKeyboardMarkup argument value.
			InlineKeyboardMarkup *models.InlineKeyboardMarkup
		}
		// SendText holds details about calls to the SendText method.
		SendText []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// S is the s argument value.
			S string
		}
	}
	lockPin               sync.RWMutex
	lockSendMarkdown      sync.RWMutex
	lockSendMarkdownPhoto sync.RWMutex
	lockSendPhoto         sync.RWMutex
	lockSendText          sync.RWMutex
}

// Pin calls PinFunc.
func (mock *MoqCreateChallengePublisher) Pin(context1 context.Context, n int64, n1 int) error {
	callInfo := struct {
		Context1 context.Context
		N        int64
		N1       int
	}{
		Context1: context1,
		N:        n,
		N1:       n1,
	}
	mock.lockPin.Lock()
	mock.calls.Pin = append(mock.calls.Pin, callInfo)
	mock.lockPin.Unlock()
	if mock.PinFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.PinFunc(context1, n, n1)
}

// PinCalls gets all the calls that were made to Pin.
// Check the length with:
//
//	len(mockedcreateChallengePublisher.PinCalls())
func (mock *MoqCreateChallengePublisher) PinCalls() []struct {
	Context1 context.Context
	N        int64
	N1       int
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		N1       int
	}
	mock.lockPin.RLock()
	calls = mock.calls.Pin
	mock.lockPin.RUnlock()
	return calls
}

// SendMarkdown calls SendMarkdownFunc.
func (mock *MoqCreateChallengePublisher) SendMarkdown(context1 context.Context, n int64, s string) (int, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		S        string
	}{
		Context1: context1,
		N:        n,
		S:        s,
	}
	mock.lockSendMarkdown.Lock()
	mock.calls.SendMarkdown = append(mock.calls.SendMarkdown, callInfo)
	mock.lockSendMarkdown.Unlock()
	if mock.SendMarkdownFunc == nil {
		var (
			n1  int
			err error
		)
		return n1, err
	}
	return mock.SendMarkdownFunc(context1, n, s)
}

// SendMarkdownCalls gets all the calls that were made to SendMarkdown.
// Check the length with:
//
//	len(mockedcreateChallengePublisher.SendMarkdownCalls())
func (mock *MoqCreateChallengePublisher) SendMarkdownCalls() []struct {
	Context1 context.Context
	N        int64
	S        string
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		S        string
	}
	mock.lockSendMarkdown.RLock()
	calls = mock.calls.SendMarkdown
	mock.lockSendMarkdown.RUnlock()
	return calls
}

// SendMarkdownPhoto calls SendMarkdownPhotoFunc.
func (mock *MoqCreateChallengePublisher) SendMarkdownPhoto(context1 context.Context, n int64, s string, s1 string) (int, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		S        string
		S1       string
	}{
		Context1: context1,
		N:        n,
		S:        s,
		S1:       s1,
	}
	mock.lockSendMarkdownPhoto.Lock()
	mock.calls.SendMarkdownPhoto = append(mock.calls.SendMarkdownPhoto, callInfo)
	mock.lockSendMarkdownPhoto.Unlock()
	if mock.SendMarkdownPhotoFunc == nil {
		var (
			n1  int
			err error
		)
		return n1, err
	}
	return mock.SendMarkdownPhotoFunc(context1, n, s, s1)
}

// SendMarkdownPhotoCalls gets all the calls that were made to SendMarkdownPhoto.
// Check the length with:
//
//	len(mockedcreateChallengePublisher.SendMarkdownPhotoCalls())
func (mock *MoqCreateChallengePublisher) SendMarkdownPhotoCalls() []struct {
	Context1 context.Context
	N        int64
	S        string
	S1       string
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		S        string
		S1       string
	}
	mock.lockSendMarkdownPhoto.RLock()
	calls = mock.calls.SendMarkdownPhoto
	mock.lockSendMarkdownPhoto.RUnlock()
	return calls
}

// SendPhoto calls SendPhotoFunc.
func (mock *MoqCreateChallengePublisher) SendPhoto(context1 context.Context, n int64, s string, s1 string, inlineKeyboardMarkup *models.InlineKeyboardMarkup) (int, error) {
	callInfo := struct {
		Context1             context.Context
		N                    int64
		S                    string
		S1                   string
		InlineKeyboardMarkup *models.InlineKeyboardMarkup
	}{
		Context1:             context1,
		N:                    n,
		S:                    s,
		S1:                   s1,
		InlineKeyboardMarkup: inlineKeyboardMarkup,
	}
	mock.lockSendPhoto.Lock()
	mock.calls.SendPhoto = append(mock.calls.SendPhoto, callInfo)
	mock.lockSendPhoto.Unlock()
	if mock.SendPhotoFunc == nil {
		var (
			n1  int
			err error
		)
		return n1, err
	}
	return mock.SendPhotoFunc(context1, n, s, s1, inlineKeyboardMarkup)
}

// SendPhotoCalls gets all the calls that were made to SendPhoto.
// Check the length with:
//
//	len(mockedcreateChallengePublisher.SendPhotoCalls())
func (mock *MoqCreateChallengePublisher) SendPhotoCalls() []struct {
	Context1             context.Context
	N                    int64
	S                    string
	S1                   string
	InlineKeyboardMarkup *models.InlineKeyboardMarkup
} {
	var calls []struct {
		Context1             context.Context
		N                    int64
		S                    string
		S1                   string
		InlineKeyboardMarkup *models.InlineKeyboardMarkup
	}
	mock.lockSendPhoto.RLock()
	calls = mock.calls.SendPhoto
	mock.lockSendPhoto.RUnlock()
	return calls
}

// SendText calls SendTextFunc.
func (mock *MoqCreateChallengePublisher) SendText(context1 context.Context, n int64, s string) (int, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		S        string
	}{
		Context1: context1,
		N:        n,
		S:        s,
	}
	mock.lockSendText.Lock()
	mock.calls.SendText = append(mock.calls.SendText, callInfo)
	mock.lockSendText.Unlock()
	if mock.SendTextFunc == nil {
		var (
			n1  int
			err error
		)
		return n1, err
	}
	return mock.SendTextFunc(context1, n, s)
}

// SendTextCalls gets all the calls that were made to SendText.
// Check the length with:
//
//	len(mockedcreateChallengePublisher.SendTextCalls())
func (mock *MoqCreateChallengePublisher) SendTextCalls() []struct {
	Context1 context.Context
	N        int64
	S        string
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		S        string
	}
	mock.lockSendText.RLock()
	calls = mock.calls.SendText
	mock.lockSendText.RUnlock()
	return calls
}
