// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package admin

import (
	"context"
	"sync"
	"time"

	"github.com/TiraelSedai/PhotoChallengeBot/internal/repository"
)

// Ensure that MoqFinishVoteChallenges does implement finishVoteChallenges.
// If this is not the case, regenerate this file with mockery.
var _ finishVoteChallenges = &MoqFinishVoteChallenges{}

// MoqFinishVoteChallenges is a mock implementation of finishVoteChallenges.
//
//	func TestSomethingThatUsesfinishVoteChallenges(t *testing.T) {
//
//		// make and configure a mocked finishVoteChallenges
//		mockedfinishVoteChallenges := &MoqFinishVoteChallenges{
//			FindOpenByMainChatIDFunc: func(context1 context.Context, n int64) (*repository.Challenge, error) {
//				panic("mock out the FindOpenByMainChatID method")
//			},
//			FinishVotingNowFunc: func(context1 context.Context, n int64, time1 time.Time) (bool, error) {
//				panic("mock out the FinishVotingNow method")
//			},
//		}
//
//		// use mockedfinishVoteChallenges in code that requires finishVoteChallenges
//		// and then make assertions.
//
//	}
type MoqFinishVoteChallenges struct {
	// FindOpenByMainChatIDFunc mocks the FindOpenByMainChatID method.
	FindOpenByMainChatIDFunc func(context1 context.Context, n int64) (*repository.Challenge, error)

	// FinishVotingNowFunc mocks the FinishVotingNow method.
	FinishVotingNowFunc func(context1 context.Context, n int64, time1 time.Time) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// FindOpenByMainChatID holds details about calls to the FindOpenByMainChatID method.
		FindOpenByMainChatID []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
		}
		// FinishVotingNow holds details about calls to the FinishVotingNow method.
		FinishVotingNow []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// Time1 is the time1 argument value.
			Time1 time.Time
		}
	}
	lockFindOpenByMainChatID sync.RWMutex
	lockFinishVotingNow      sync.RWMutex
}

// FindOpenByMainChatID calls FindOpenByMainChatIDFunc.
func (mock *MoqFinishVoteChallenges) FindOpenByMainChatID(context1 context.Context, n int64) (*repository.Challenge, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
	}{
		Context1: context1,
		N:        n,
	}
	mock.lockFindOpenByMainChatID.Lock()
	mock.calls.FindOpenByMainChatID = append(mock.calls.FindOpenByMainChatID, callInfo)
	mock.lockFindOpenByMainChatID.Unlock()
	if mock.FindOpenByMainChatIDFunc == nil {
		var (
			challenge *repository.Challenge
			err       error
		)
		return challenge, err
	}
	return mock.FindOpenByMainChatIDFunc(context1, n)
}

// FindOpenByMainChatIDCalls gets all the calls that were made to FindOpenByMainChatID.
// Check the length with:
//
//	len(mockedfinishVoteChallenges.FindOpenByMainChatIDCalls())
func (mock *MoqFinishVoteChallenges) FindOpenByMainChatIDCalls() []struct {
	Context1 context.Context
	N        int64
} {
	var calls []struct {
		Context1 context.Context
		N        int64
	}
	mock.lockFindOpenByMainChatID.RLock()
	calls = mock.calls.FindOpenByMainChatID
	mock.lockFindOpenByMainChatID.RUnlock()
	return calls
}

// FinishVotingNow calls FinishVotingNowFunc.
func (mock *MoqFinishVoteChallenges) FinishVotingNow(context1 context.Context, n int64, time1 time.Time) (bool, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
	}{
		Context1: context1,
		N:        n,
		Time1:    time1,
	}
	mock.lockFinishVotingNow.Lock()
	mock.calls.FinishVotingNow = append(mock.calls.FinishVotingNow, callInfo)
	mock.lockFinishVotingNow.Unlock()
	if mock.FinishVotingNowFunc == nil {
		var (
			b   bool
			err error
		)
		return b, err
	}
	return mock.FinishVotingNowFunc(context1, n, time1)
}

// FinishVotingNowCalls gets all the calls that were made to FinishVotingNow.
// Check the length with:
//
//	len(mockedfinishVoteChallenges.FinishVotingNowCalls())
func (mock *MoqFinishVoteChallenges) FinishVotingNowCalls() []struct {
	Context1 context.Context
	N        int64
	Time1    time.Time
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
	}
	mock.lockFinishVotingNow.RLock()
	calls = mock.calls.FinishVotingNow
	mock.lockFinishVotingNow.RUnlock()
	return calls
}
