// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package admin

import (
	"context"
	"sync"

	"github.com/go-telegram/bot/models"
)

// Ensure that MoqFinishVoteCommandHandler does implement finishVoteCommandHandler.
// If this is not the case, regenerate this file with mockery.
var _ finishVoteCommandHandler = &MoqFinishVoteCommandHandler{}

// MoqFinishVoteCommandHandler is a mock implementation of finishVoteCommandHandler.
//
//	func TestSomethingThatUsesfinishVoteCommandHandler(t *testing.T) {
//
//		// make and configure a mocked finishVoteCommandHandler
//		mockedfinishVoteCommandHandler := &MoqFinishVoteCommandHandler{
//			HandleAdminChatMessageFunc: func(context1 context.Context, message *models.Message) error {
//				panic("mock out the HandleAdminChatMessage method")
//			},
//			HandlesFunc: func(s string) bool {
//				panic("mock out the Handles method")
//			},
//		}
//
//		// use mockedfinishVoteCommandHandler in code that requires finishVoteCommandHandler
//		// and then make assertions.
//
//	}
type MoqFinishVoteCommandHandler struct {
	// HandleAdminChatMessageFunc mocks the HandleAdminChatMessage method.
	HandleAdminChatMessageFunc func(context1 context.Context, message *models.Message) error

	// HandlesFunc mocks the Handles method.
	HandlesFunc func(s string) bool

	// calls tracks calls to the methods.
	calls struct {
		// HandleAdminChatMessage holds details about calls to the HandleAdminChatMessage method.
		HandleAdminChatMessage []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// Message is the message argument value.
			Message *models.Message
		}
		// Handles holds details about calls to the Handles method.
		Handles []struct {
			// S is the s argument value.
			S string
		}
	}
	lockHandleAdminChatMessage sync.RWMutex
	lockHandles                sync.RWMutex
}

// HandleAdminChatMessage calls HandleAdminChatMessageFunc.
func (mock *MoqFinishVoteCommandHandler) HandleAdminChatMessage(context1 context.Context, message *models.Message) error {
	callInfo := struct {
		Context1 context.Context
		Message  *models.Message
	}{
		Context1: context1,
		Message:  message,
	}
	mock.lockHandleAdminChatMessage.Lock()
	mock.calls.HandleAdminChatMessage = append(mock.calls.HandleAdminChatMessage, callInfo)
	mock.lockHandleAdminChatMessage.Unlock()
	if mock.HandleAdminChatMessageFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.HandleAdminChatMessageFunc(context1, message)
}

// HandleAdminChatMessageCalls gets all the calls that were made to HandleAdminChatMessage.
// Check the length with:
//
//	len(mockedfinishVoteCommandHandler.HandleAdminChatMessageCalls())
func (mock *MoqFinishVoteCommandHandler) HandleAdminChatMessageCalls() []struct {
	Context1 context.Context
	Message  *models.Message
} {
	var calls []struct {
		Context1 context.Context
		Message  *models.Message
	}
	mock.lockHandleAdminChatMessage.RLock()
	calls = mock.calls.HandleAdminChatMessage
	mock.lockHandleAdminChatMessage.RUnlock()
	return calls
}

// Handles calls HandlesFunc.
func (mock *MoqFinishVoteCommandHandler) Handles(s string) bool {
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockHandles.Lock()
	mock.calls.Handles = append(mock.calls.Handles, callInfo)
	mock.lockHandles.Unlock()
	if mock.HandlesFunc == nil {
		var (
			b bool
		)
		return b
	}
	return mock.HandlesFunc(s)
}

// HandlesCalls gets all the calls that were made to Handles.
// Check the length with:
//
//	len(mockedfinishVoteCommandHandler.HandlesCalls())
func (mock *MoqFinishVoteCommandHandler) HandlesCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockHandles.RLock()
	calls = mock.calls.Handles
	mock.lockHandles.RUnlock()
	return calls
}
