// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package admin

import (
	"context"
	"sync"

	"github.com/TiraelSedai/PhotoChallengeBot/internal/repository"
)

// Ensure that MoqFinishVoteTopics does implement finishVoteTopics.
// If this is not the case, regenerate this file with mockery.
var _ finishVoteTopics = &MoqFinishVoteTopics{}

// MoqFinishVoteTopics is a mock implementation of finishVoteTopics.
//
//	func TestSomethingThatUsesfinishVoteTopics(t *testing.T) {
//
//		// make and configure a mocked finishVoteTopics
//		mockedfinishVoteTopics := &MoqFinishVoteTopics{
//			PublishOneFunc: func(context1 context.Context, challenge repository.Challenge) error {
//				panic("mock out the PublishOne method")
//			},
//		}
//
//		// use mockedfinishVoteTopics in code that requires finishVoteTopics
//		// and then make assertions.
//
//	}
type MoqFinishVoteTopics struct {
	// PublishOneFunc mocks the PublishOne method.
	PublishOneFunc func(context1 context.Context, challenge repository.Challenge) error

	// calls tracks calls to the methods.
	calls struct {
		// PublishOne holds details about calls to the PublishOne method.
		PublishOne []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// Challenge is the challenge argument value.
			Challenge repository.Challenge
		}
	}
	lockPublishOne sync.RWMutex
}

// PublishOne calls PublishOneFunc.
func (mock *MoqFinishVoteTopics) PublishOne(context1 context.Context, challenge repository.Challenge) error {
	callInfo := struct {
		Context1  context.Context
		Challenge repository.Challenge
	}{
		Context1:  context1,
		Challenge: challenge,
	}
	mock.lockPublishOne.Lock()
	mock.calls.PublishOne = append(mock.calls.PublishOne, callInfo)
	mock.lockPublishOne.Unlock()
	if mock.PublishOneFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.PublishOneFunc(context1, challenge)
}

// PublishOneCalls gets all the calls that were made to PublishOne.
// Check the length with:
//
//	len(mockedfinishVoteTopics.PublishOneCalls())
func (mock *MoqFinishVoteTopics) PublishOneCalls() []struct {
	Context1  context.Context
	Challenge repository.Challenge
} {
	var calls []struct {
		Context1  context.Context
		Challenge repository.Challenge
	}
	mock.lockPublishOne.RLock()
	calls = mock.calls.PublishOne
	mock.lockPublishOne.RUnlock()
	return calls
}
