// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package admin

import (
	"context"
	"sync"
)

// Ensure that MoqFinishVotePublisher does implement finishVotePublisher.
// If this is not the case, regenerate this file with mockery.
var _ finishVotePublisher = &MoqFinishVotePublisher{}

// MoqFinishVotePublisher is a mock implementation of finishVotePublisher.
//
//	func TestSomethingThatUsesfinishVotePublisher(t *testing.T) {
//
//		// make and configure a mocked finishVotePublisher
//		mockedfinishVotePublisher := &MoqFinishVotePublisher{
//			SendTextFunc: func(context1 context.Context, n int64, s string) (int, error) {
//				panic("mock out the SendText method")
//			},
//		}
//
//		// use mockedfinishVotePublisher in code that requires finishVotePublisher
//		// and then make assertions.
//
//	}
type MoqFinishVotePublisher struct {
	// SendTextFunc mocks the SendText method.
	SendTextFunc func(context1 context.Context, n int64, s string) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// SendText holds details about calls to the SendText method.
		SendText []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// S is the s argument value.
			S string
		}
	}
	lockSendText sync.RWMutex
}

// SendText calls SendTextFunc.
func (mock *MoqFinishVotePublisher) SendText(context1 context.Context, n int64, s string) (int, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		S        string
	}{
		Context1: context1,
		N:        n,
		S:        s,
	}
	mock.lockSendText.Lock()
	mock.calls.SendText = append(mock.calls.SendText, callInfo)
	mock.lockSendText.Unlock()
	if mock.SendTextFunc == nil {
		var (
			n1  int
			err error
		)
		return n1, err
	}
	return mock.SendTextFunc(context1, n, s)
}

// SendTextCalls gets all the calls that were made to SendText.
// Check the length with:
//
//	len(mockedfinishVotePublisher.SendTextCalls())
func (mock *MoqFinishVotePublisher) SendTextCalls() []struct {
	Context1 context.Context
	N        int64
	S        string
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		S        string
	}
	mock.lockSendText.RLock()
	calls = mock.calls.SendText
	mock.lockSendText.RUnlock()
	return calls
}
