// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package admin

import (
	"context"
	"sync"

	"github.com/TiraelSedai/PhotoChallengeBot/internal/repository"
)

// Ensure that MoqOpenChallengeFinder does implement openChallengeFinder.
// If this is not the case, regenerate this file with mockery.
var _ openChallengeFinder = &MoqOpenChallengeFinder{}

// MoqOpenChallengeFinder is a mock implementation of openChallengeFinder.
//
//	func TestSomethingThatUsesopenChallengeFinder(t *testing.T) {
//
//		// make and configure a mocked openChallengeFinder
//		mockedopenChallengeFinder := &MoqOpenChallengeFinder{
//			FindOpenByMainChatIDFunc: func(context1 context.Context, n int64) (*repository.Challenge, error) {
//				panic("mock out the FindOpenByMainChatID method")
//			},
//		}
//
//		// use mockedopenChallengeFinder in code that requires openChallengeFinder
//		// and then make assertions.
//
//	}
type MoqOpenChallengeFinder struct {
	// FindOpenByMainChatIDFunc mocks the FindOpenByMainChatID method.
	FindOpenByMainChatIDFunc func(context1 context.Context, n int64) (*repository.Challenge, error)

	// calls tracks calls to the methods.
	calls struct {
		// FindOpenByMainChatID holds details about calls to the FindOpenByMainChatID method.
		FindOpenByMainChatID []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
		}
	}
	lockFindOpenByMainChatID sync.RWMutex
}

// FindOpenByMainChatID calls FindOpenByMainChatIDFunc.
func (mock *MoqOpenChallengeFinder) FindOpenByMainChatID(context1 context.Context, n int64) (*repository.Challenge, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
	}{
		Context1: context1,
		N:        n,
	}
	mock.lockFindOpenByMainChatID.Lock()
	mock.calls.FindOpenByMainChatID = append(mock.calls.FindOpenByMainChatID, callInfo)
	mock.lockFindOpenByMainChatID.Unlock()
	if mock.FindOpenByMainChatIDFunc == nil {
		var (
			challenge *repository.Challenge
			err       error
		)
		return challenge, err
	}
	return mock.FindOpenByMainChatIDFunc(context1, n)
}

// FindOpenByMainChatIDCalls gets all the calls that were made to FindOpenByMainChatID.
// Check the length with:
//
//	len(mockedopenChallengeFinder.FindOpenByMainChatIDCalls())
func (mock *MoqOpenChallengeFinder) FindOpenByMainChatIDCalls() []struct {
	Context1 context.Context
	N        int64
} {
	var calls []struct {
		Context1 context.Context
		N        int64
	}
	mock.lockFindOpenByMainChatID.RLock()
	calls = mock.calls.FindOpenByMainChatID
	mock.lockFindOpenByMainChatID.RUnlock()
	return calls
}
