// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package admin

import (
	"context"
	"sync"

	"github.com/TiraelSedai/PhotoChallengeBot/internal/repository"
)

// Ensure that MoqPhotoDeleter does implement photoDeleter.
// If this is not the case, regenerate this file with mockery.
var _ photoDeleter = &MoqPhotoDeleter{}

// MoqPhotoDeleter is a mock implementation of photoDeleter.
//
//	func TestSomethingThatUsesphotoDeleter(t *testing.T) {
//
//		// make and configure a mocked photoDeleter
//		mockedphotoDeleter := &MoqPhotoDeleter{
//			DeleteByAuthorIDFunc: func(context1 context.Context, n int64, n1 int64) (*repository.Photo, error) {
//				panic("mock out the DeleteByAuthorID method")
//			},
//			DeleteByUsernameFunc: func(context1 context.Context, n int64, s string) (*repository.Photo, error) {
//				panic("mock out the DeleteByUsername method")
//			},
//		}
//
//		// use mockedphotoDeleter in code that requires photoDeleter
//		// and then make assertions.
//
//	}
type MoqPhotoDeleter struct {
	// DeleteByAuthorIDFunc mocks the DeleteByAuthorID method.
	DeleteByAuthorIDFunc func(context1 context.Context, n int64, n1 int64) (*repository.Photo, error)

	// DeleteByUsernameFunc mocks the DeleteByUsername method.
	DeleteByUsernameFunc func(context1 context.Context, n int64, s string) (*repository.Photo, error)

	// calls tracks calls to the methods.
	calls struct {
		// DeleteByAuthorID holds details about calls to the DeleteByAuthorID method.
		DeleteByAuthorID []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// N1 is the n1 argument value.
			N1 int64
		}
		// DeleteByUsername holds details about calls to the DeleteByUsername method.
		DeleteByUsername []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// S is the s argument value.
			S string
		}
	}
	lockDeleteByAuthorID sync.RWMutex
	lockDeleteByUsername sync.RWMutex
}

// DeleteByAuthorID calls DeleteByAuthorIDFunc.
func (mock *MoqPhotoDeleter) DeleteByAuthorID(context1 context.Context, n int64, n1 int64) (*repository.Photo, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		N1       int64
	}{
		Context1: context1,
		N:        n,
		N1:       n1,
	}
	mock.lockDeleteByAuthorID.Lock()
	mock.calls.DeleteByAuthorID = append(mock.calls.DeleteByAuthorID, callInfo)
	mock.lockDeleteByAuthorID.Unlock()
	if mock.DeleteByAuthorIDFunc == nil {
		var (
			photo *repository.Photo
			err   error
		)
		return photo, err
	}
	return mock.DeleteByAuthorIDFunc(context1, n, n1)
}

// DeleteByAuthorIDCalls gets all the calls that were made to DeleteByAuthorID.
// Check the length with:
//
//	len(mockedphotoDeleter.DeleteByAuthorIDCalls())
func (mock *MoqPhotoDeleter) DeleteByAuthorIDCalls() []struct {
	Context1 context.Context
	N        int64
	N1       int64
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		N1       int64
	}
	mock.lockDeleteByAuthorID.RLock()
	calls = mock.calls.DeleteByAuthorID
	mock.lockDeleteByAuthorID.RUnlock()
	return calls
}

// DeleteByUsername calls DeleteByUsernameFunc.
func (mock *MoqPhotoDeleter) DeleteByUsername(context1 context.Context, n int64, s string) (*repository.Photo, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		S        string
	}{
		Context1: context1,
		N:        n,
		S:        s,
	}
	mock.lockDeleteByUsername.Lock()
	mock.calls.DeleteByUsername = append(mock.calls.DeleteByUsername, callInfo)
	mock.lockDeleteByUsername.Unlock()
	if mock.DeleteByUsernameFunc == nil {
		var (
			photo *repository.Photo
			err   error
		)
		return photo, err
	}
	return mock.DeleteByUsernameFunc(context1, n, s)
}

// DeleteByUsernameCalls gets all the calls that were made to DeleteByUsername.
// Check the length with:
//
//	len(mockedphotoDeleter.DeleteByUsernameCalls())
func (mock *MoqPhotoDeleter) DeleteByUsernameCalls() []struct {
	Context1 context.Context
	N        int64
	S        string
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		S        string
	}
	mock.lockDeleteByUsername.RLock()
	calls = mock.calls.DeleteByUsername
	mock.lockDeleteByUsername.RUnlock()
	return calls
}
