// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package admin

import (
	"context"
	"sync"

	"github.com/TiraelSedai/PhotoChallengeBot/internal/repository"
)

// Ensure that MoqSessionStore does implement sessionStore.
// If this is not the case, regenerate this file with mockery.
var _ sessionStore = &MoqSessionStore{}

// MoqSessionStore is a mock implementation of sessionStore.
//
//	func TestSomethingThatUsessessionStore(t *testing.T) {
//
//		// make and configure a mocked sessionStore
//		mockedsessionStore := &MoqSessionStore{
//			ClearFunc: func(context1 context.Context, n int64, n1 int64) error {
//				panic("mock out the Clear method")
//			},
//			GetFunc: func(context1 context.Context, n int64, n1 int64) (*repository.AdminSession, error) {
//				panic("mock out the Get method")
//			},
//			UpsertFunc: func(context1 context.Context, adminSession repository.AdminSession) (repository.AdminSession, error) {
//				panic("mock out the Upsert method")
//			},
//		}
//
//		// use mockedsessionStore in code that requires sessionStore
//		// and then make assertions.
//
//	}
type MoqSessionStore struct {
	// ClearFunc mocks the Clear method.
	ClearFunc func(context1 context.Context, n int64, n1 int64) error

	// GetFunc mocks the Get method.
	GetFunc func(context1 context.Context, n int64, n1 int64) (*repository.AdminSession, error)

	// UpsertFunc mocks the Upsert method.
	UpsertFunc func(context1 context.Context, adminSession repository.AdminSession) (repository.AdminSession, error)

	// calls tracks calls to the methods.
	calls struct {
		// Clear holds details about calls to the Clear method.
		Clear []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// N1 is the n1 argument value.
			N1 int64
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// N1 is the n1 argument value.
			N1 int64
		}
		// Upsert holds details about calls to the Upsert method.
		Upsert []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// AdminSession is the adminSession argument value.
			AdminSession repository.AdminSession
		}
	}
	lockClear  sync.RWMutex
	lockGet    sync.RWMutex
	lockUpsert sync.RWMutex
}

// Clear calls ClearFunc.
func (mock *MoqSessionStore) Clear(context1 context.Context, n int64, n1 int64) error {
	callInfo := struct {
		Context1 context.Context
		N        int64
		N1       int64
	}{
		Context1: context1,
		N:        n,
		N1:       n1,
	}
	mock.lockClear.Lock()
	mock.calls.Clear = append(mock.calls.Clear, callInfo)
	mock.lockClear.Unlock()
	if mock.ClearFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.ClearFunc(context1, n, n1)
}

// ClearCalls gets all the calls that were made to Clear.
// Check the length with:
//
//	len(mockedsessionStore.ClearCalls())
func (mock *MoqSessionStore) ClearCalls() []struct {
	Context1 context.Context
	N        int64
	N1       int64
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		N1       int64
	}
	mock.lockClear.RLock()
	calls = mock.calls.Clear
	mock.lockClear.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *MoqSessionStore) Get(context1 context.Context, n int64, n1 int64) (*repository.AdminSession, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		N1       int64
	}{
		Context1: context1,
		N:        n,
		N1:       n1,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			adminSession *repository.AdminSession
			err          error
		)
		return adminSession, err
	}
	return mock.GetFunc(context1, n, n1)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedsessionStore.GetCalls())
func (mock *MoqSessionStore) GetCalls() []struct {
	Context1 context.Context
	N        int64
	N1       int64
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		N1       int64
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Upsert calls UpsertFunc.
func (mock *MoqSessionStore) Upsert(context1 context.Context, adminSession repository.AdminSession) (repository.AdminSession, error) {
	callInfo := struct {
		Context1     context.Context
		AdminSession repository.AdminSession
	}{
		Context1:     context1,
		AdminSession: adminSession,
	}
	mock.lockUpsert.Lock()
	mock.calls.Upsert = append(mock.calls.Upsert, callInfo)
	mock.lockUpsert.Unlock()
	if mock.UpsertFunc == nil {
		var (
			adminSession1 repository.AdminSession
			err           error
		)
		return adminSession1, err
	}
	return mock.UpsertFunc(context1, adminSession)
}

// UpsertCalls gets all the calls that were made to Upsert.
// Check the length with:
//
//	len(mockedsessionStore.UpsertCalls())
func (mock *MoqSessionStore) UpsertCalls() []struct {
	Context1     context.Context
	AdminSession repository.AdminSession
} {
	var calls []struct {
		Context1     context.Context
		AdminSession repository.AdminSession
	}
	mock.lockUpsert.RLock()
	calls = mock.calls.Upsert
	mock.lockUpsert.RUnlock()
	return calls
}
