// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package admin

import (
	"context"
	"sync"

	"github.com/TiraelSedai/PhotoChallengeBot/internal/repository"
)

// Ensure that MoqUserStore does implement userStore.
// If this is not the case, regenerate this file with mockery.
var _ userStore = &MoqUserStore{}

// MoqUserStore is a mock implementation of userStore.
//
//	func TestSomethingThatUsesuserStore(t *testing.T) {
//
//		// make and configure a mocked userStore
//		mockeduserStore := &MoqUserStore{
//			UpsertFunc: func(context1 context.Context, user repository.User) (repository.User, error) {
//				panic("mock out the Upsert method")
//			},
//		}
//
//		// use mockeduserStore in code that requires userStore
//		// and then make assertions.
//
//	}
type MoqUserStore struct {
	// UpsertFunc mocks the Upsert method.
	UpsertFunc func(context1 context.Context, user repository.User) (repository.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// Upsert holds details about calls to the Upsert method.
		Upsert []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// User is the user argument value.
			User repository.User
		}
	}
	lockUpsert sync.RWMutex
}

// Upsert calls UpsertFunc.
func (mock *MoqUserStore) Upsert(context1 context.Context, user repository.User) (repository.User, error) {
	callInfo := struct {
		Context1 context.Context
		User     repository.User
	}{
		Context1: context1,
		User:     user,
	}
	mock.lockUpsert.Lock()
	mock.calls.Upsert = append(mock.calls.Upsert, callInfo)
	mock.lockUpsert.Unlock()
	if mock.UpsertFunc == nil {
		var (
			user1 repository.User
			err   error
		)
		return user1, err
	}
	return mock.UpsertFunc(context1, user)
}

// UpsertCalls gets all the calls that were made to Upsert.
// Check the length with:
//
//	len(mockeduserStore.UpsertCalls())
func (mock *MoqUserStore) UpsertCalls() []struct {
	Context1 context.Context
	User     repository.User
} {
	var calls []struct {
		Context1 context.Context
		User     repository.User
	}
	mock.lockUpsert.RLock()
	calls = mock.calls.Upsert
	mock.lockUpsert.RUnlock()
	return calls
}
