// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package topic

import (
	"context"
	"sync"
	"time"

	"github.com/TiraelSedai/PhotoChallengeBot/internal/repository"
)

// Ensure that MoqReportChallenges does implement reportChallenges.
// If this is not the case, regenerate this file with mockery.
var _ reportChallenges = &MoqReportChallenges{}

// MoqReportChallenges is a mock implementation of reportChallenges.
//
//	func TestSomethingThatUsesreportChallenges(t *testing.T) {
//
//		// make and configure a mocked reportChallenges
//		mockedreportChallenges := &MoqReportChallenges{
//			ClaimTopicReportFunc: func(context1 context.Context, n int64, time1 time.Time) (bool, error) {
//				panic("mock out the ClaimTopicReport method")
//			},
//			ListUnsentTopicReportsFunc: func(context1 context.Context, n int64, n1 int) ([]repository.Challenge, error) {
//				panic("mock out the ListUnsentTopicReports method")
//			},
//			MarkTopicReportSentFunc: func(context1 context.Context, n int64, time1 time.Time, time11 time.Time) (bool, error) {
//				panic("mock out the MarkTopicReportSent method")
//			},
//			ReleaseTopicReportClaimFunc: func(context1 context.Context, n int64, time1 time.Time) error {
//				panic("mock out the ReleaseTopicReportClaim method")
//			},
//		}
//
//		// use mockedreportChallenges in code that requires reportChallenges
//		// and then make assertions.
//
//	}
type MoqReportChallenges struct {
	// ClaimTopicReportFunc mocks the ClaimTopicReport method.
	ClaimTopicReportFunc func(context1 context.Context, n int64, time1 time.Time) (bool, error)

	// ListUnsentTopicReportsFunc mocks the ListUnsentTopicReports method.
	ListUnsentTopicReportsFunc func(context1 context.Context, n int64, n1 int) ([]repository.Challenge, error)

	// MarkTopicReportSentFunc mocks the MarkTopicReportSent method.
	MarkTopicReportSentFunc func(context1 context.Context, n int64, time1 time.Time, time11 time.Time) (bool, error)

	// ReleaseTopicReportClaimFunc mocks the ReleaseTopicReportClaim method.
	ReleaseTopicReportClaimFunc func(context1 context.Context, n int64, time1 time.Time) error

	// calls tracks calls to the methods.
	calls struct {
		// ClaimTopicReport holds details about calls to the ClaimTopicReport method.
		ClaimTopicReport []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// Time1 is the time1 argument value.
			Time1 time.Time
		}
		// ListUnsentTopicReports holds details about calls to the ListUnsentTopicReports method.
		ListUnsentTopicReports []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// N1 is the n1 argument value.
			N1 int
		}
		// MarkTopicReportSent holds details about calls to the MarkTopicReportSent method.
		MarkTopicReportSent []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// Time1 is the time1 argument value.
			Time1 time.Time
			// Time11 is the time11 argument value.
			Time11 time.Time
		}
		// ReleaseTopicReportClaim holds details about calls to the ReleaseTopicReportClaim method.
		ReleaseTopicReportClaim []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// Time1 is the time1 argument value.
			Time1 time.Time
		}
	}
	lockClaimTopicReport        sync.RWMutex
	lockListUnsentTopicReports  sync.RWMutex
	lockMarkTopicReportSent     sync.RWMutex
	lockReleaseTopicReportClaim sync.RWMutex
}

// ClaimTopicReport calls ClaimTopicReportFunc.
func (mock *MoqReportChallenges) ClaimTopicReport(context1 context.Context, n int64, time1 time.Time) (bool, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
	}{
		Context1: context1,
		N:        n,
		Time1:    time1,
	}
	mock.lockClaimTopicReport.Lock()
	mock.calls.ClaimTopicReport = append(mock.calls.ClaimTopicReport, callInfo)
	mock.lockClaimTopicReport.Unlock()
	if mock.ClaimTopicReportFunc == nil {
		var (
			b   bool
			err error
		)
		return b, err
	}
	return mock.ClaimTopicReportFunc(context1, n, time1)
}

// ClaimTopicReportCalls gets all the calls that were made to ClaimTopicReport.
// Check the length with:
//
//	len(mockedreportChallenges.ClaimTopicReportCalls())
func (mock *MoqReportChallenges) ClaimTopicReportCalls() []struct {
	Context1 context.Context
	N        int64
	Time1    time.Time
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
	}
	mock.lockClaimTopicReport.RLock()
	calls = mock.calls.ClaimTopicReport
	mock.lockClaimTopicReport.RUnlock()
	return calls
}

// ListUnsentTopicReports calls ListUnsentTopicReportsFunc.
func (mock *MoqReportChallenges) ListUnsentTopicReports(context1 context.Context, n int64, n1 int) ([]repository.Challenge, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		N1       int
	}{
		Context1: context1,
		N:        n,
		N1:       n1,
	}
	mock.lockListUnsentTopicReports.Lock()
	mock.calls.ListUnsentTopicReports = append(mock.calls.ListUnsentTopicReports, callInfo)
	mock.lockListUnsentTopicReports.Unlock()
	if mock.ListUnsentTopicReportsFunc == nil {
		var (
			challenges []repository.Challenge
			err        error
		)
		return challenges, err
	}
	return mock.ListUnsentTopicReportsFunc(context1, n, n1)
}

// ListUnsentTopicReportsCalls gets all the calls that were made to ListUnsentTopicReports.
// Check the length with:
//
//	len(mockedreportChallenges.ListUnsentTopicReportsCalls())
func (mock *MoqReportChallenges) ListUnsentTopicReportsCalls() []struct {
	Context1 context.Context
	N        int64
	N1       int
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		N1       int
	}
	mock.lockListUnsentTopicReports.RLock()
	calls = mock.calls.ListUnsentTopicReports
	mock.lockListUnsentTopicReports.RUnlock()
	return calls
}

// MarkTopicReportSent calls MarkTopicReportSentFunc.
func (mock *MoqReportChallenges) MarkTopicReportSent(context1 context.Context, n int64, time1 time.Time, time11 time.Time) (bool, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
		Time11   time.Time
	}{
		Context1: context1,
		N:        n,
		Time1:    time1,
		Time11:   time11,
	}
	mock.lockMarkTopicReportSent.Lock()
	mock.calls.MarkTopicReportSent = append(mock.calls.MarkTopicReportSent, callInfo)
	mock.lockMarkTopicReportSent.Unlock()
	if mock.MarkTopicReportSentFunc == nil {
		var (
			b   bool
			err error
		)
		return b, err
	}
	return mock.MarkTopicReportSentFunc(context1, n, time1, time11)
}

// MarkTopicReportSentCalls gets all the calls that were made to MarkTopicReportSent.
// Check the length with:
//
//	len(mockedreportChallenges.MarkTopicReportSentCalls())
func (mock *MoqReportChallenges) MarkTopicReportSentCalls() []struct {
	Context1 context.Context
	N        int64
	Time1    time.Time
	Time11   time.Time
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
		Time11   time.Time
	}
	mock.lockMarkTopicReportSent.RLock()
	calls = mock.calls.MarkTopicReportSent
	mock.lockMarkTopicReportSent.RUnlock()
	return calls
}

// ReleaseTopicReportClaim calls ReleaseTopicReportClaimFunc.
func (mock *MoqReportChallenges) ReleaseTopicReportClaim(context1 context.Context, n int64, time1 time.Time) error {
	callInfo := struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
	}{
		Context1: context1,
		N:        n,
		Time1:    time1,
	}
	mock.lockReleaseTopicReportClaim.Lock()
	mock.calls.ReleaseTopicReportClaim = append(mock.calls.ReleaseTopicReportClaim, callInfo)
	mock.lockReleaseTopicReportClaim.Unlock()
	if mock.ReleaseTopicReportClaimFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.ReleaseTopicReportClaimFunc(context1, n, time1)
}

// ReleaseTopicReportClaimCalls gets all the calls that were made to ReleaseTopicReportClaim.
// Check the length with:
//
//	len(mockedreportChallenges.ReleaseTopicReportClaimCalls())
func (mock *MoqReportChallenges) ReleaseTopicReportClaimCalls() []struct {
	Context1 context.Context
	N        int64
	Time1    time.Time
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
	}
	mock.lockReleaseTopicReportClaim.RLock()
	calls = mock.calls.ReleaseTopicReportClaim
	mock.lockReleaseTopicReportClaim.RUnlock()
	return calls
}
