// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package topic

import (
	"context"
	"sync"
)

// Ensure that MoqReportPublisher does implement reportPublisher.
// If this is not the case, regenerate this file with mockery.
var _ reportPublisher = &MoqReportPublisher{}

// MoqReportPublisher is a mock implementation of reportPublisher.
//
//	func TestSomethingThatUsesreportPublisher(t *testing.T) {
//
//		// make and configure a mocked reportPublisher
//		mockedreportPublisher := &MoqReportPublisher{
//			SendTextFunc: func(context1 context.Context, n int64, s string) (int, error) {
//				panic("mock out the SendText method")
//			},
//		}
//
//		// use mockedreportPublisher in code that requires reportPublisher
//		// and then make assertions.
//
//	}
type MoqReportPublisher struct {
	// SendTextFunc mocks the SendText method.
	SendTextFunc func(context1 context.Context, n int64, s string) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// SendText holds details about calls to the SendText method.
		SendText []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// S is the s argument value.
			S string
		}
	}
	lockSendText sync.RWMutex
}

// SendText calls SendTextFunc.
func (mock *MoqReportPublisher) SendText(context1 context.Context, n int64, s string) (int, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		S        string
	}{
		Context1: context1,
		N:        n,
		S:        s,
	}
	mock.lockSendText.Lock()
	mock.calls.SendText = append(mock.calls.SendText, callInfo)
	mock.lockSendText.Unlock()
	if mock.SendTextFunc == nil {
		var (
			n1  int
			err error
		)
		return n1, err
	}
	return mock.SendTextFunc(context1, n, s)
}

// SendTextCalls gets all the calls that were made to SendText.
// Check the length with:
//
//	len(mockedreportPublisher.SendTextCalls())
func (mock *MoqReportPublisher) SendTextCalls() []struct {
	Context1 context.Context
	N        int64
	S        string
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		S        string
	}
	mock.lockSendText.RLock()
	calls = mock.calls.SendText
	mock.lockSendText.RUnlock()
	return calls
}
