// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package topic

import (
	"context"
	"sync"

	"github.com/TiraelSedai/PhotoChallengeBot/internal/repository"
)

// Ensure that MoqReportSuggestions does implement reportSuggestions.
// If this is not the case, regenerate this file with mockery.
var _ reportSuggestions = &MoqReportSuggestions{}

// MoqReportSuggestions is a mock implementation of reportSuggestions.
//
//	func TestSomethingThatUsesreportSuggestions(t *testing.T) {
//
//		// make and configure a mocked reportSuggestions
//		mockedreportSuggestions := &MoqReportSuggestions{
//			ListByChallengeFunc: func(context1 context.Context, n int64) ([]repository.TopicSuggestion, error) {
//				panic("mock out the ListByChallenge method")
//			},
//		}
//
//		// use mockedreportSuggestions in code that requires reportSuggestions
//		// and then make assertions.
//
//	}
type MoqReportSuggestions struct {
	// ListByChallengeFunc mocks the ListByChallenge method.
	ListByChallengeFunc func(context1 context.Context, n int64) ([]repository.TopicSuggestion, error)

	// calls tracks calls to the methods.
	calls struct {
		// ListByChallenge holds details about calls to the ListByChallenge method.
		ListByChallenge []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
		}
	}
	lockListByChallenge sync.RWMutex
}

// ListByChallenge calls ListByChallengeFunc.
func (mock *MoqReportSuggestions) ListByChallenge(context1 context.Context, n int64) ([]repository.TopicSuggestion, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
	}{
		Context1: context1,
		N:        n,
	}
	mock.lockListByChallenge.Lock()
	mock.calls.ListByChallenge = append(mock.calls.ListByChallenge, callInfo)
	mock.lockListByChallenge.Unlock()
	if mock.ListByChallengeFunc == nil {
		var (
			topicSuggestions []repository.TopicSuggestion
			err              error
		)
		return topicSuggestions, err
	}
	return mock.ListByChallengeFunc(context1, n)
}

// ListByChallengeCalls gets all the calls that were made to ListByChallenge.
// Check the length with:
//
//	len(mockedreportSuggestions.ListByChallengeCalls())
func (mock *MoqReportSuggestions) ListByChallengeCalls() []struct {
	Context1 context.Context
	N        int64
} {
	var calls []struct {
		Context1 context.Context
		N        int64
	}
	mock.lockListByChallenge.RLock()
	calls = mock.calls.ListByChallenge
	mock.lockListByChallenge.RUnlock()
	return calls
}
