// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package topic

import (
	"context"
	"sync"

	"github.com/TiraelSedai/PhotoChallengeBot/internal/repository"
)

// Ensure that MoqReportUsers does implement reportUsers.
// If this is not the case, regenerate this file with mockery.
var _ reportUsers = &MoqReportUsers{}

// MoqReportUsers is a mock implementation of reportUsers.
//
//	func TestSomethingThatUsesreportUsers(t *testing.T) {
//
//		// make and configure a mocked reportUsers
//		mockedreportUsers := &MoqReportUsers{
//			GetFunc: func(context1 context.Context, n int64) (repository.User, error) {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedreportUsers in code that requires reportUsers
//		// and then make assertions.
//
//	}
type MoqReportUsers struct {
	// GetFunc mocks the Get method.
	GetFunc func(context1 context.Context, n int64) (repository.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
		}
	}
	lockGet sync.RWMutex
}

// Get calls GetFunc.
func (mock *MoqReportUsers) Get(context1 context.Context, n int64) (repository.User, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
	}{
		Context1: context1,
		N:        n,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			user repository.User
			err  error
		)
		return user, err
	}
	return mock.GetFunc(context1, n)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedreportUsers.GetCalls())
func (mock *MoqReportUsers) GetCalls() []struct {
	Context1 context.Context
	N        int64
} {
	var calls []struct {
		Context1 context.Context
		N        int64
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}
