// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package topic

import (
	"context"
	"sync"

	"github.com/TiraelSedai/PhotoChallengeBot/internal/repository"
)

// Ensure that MoqSuggestions does implement suggestions.
// If this is not the case, regenerate this file with mockery.
var _ suggestions = &MoqSuggestions{}

// MoqSuggestions is a mock implementation of suggestions.
//
//	func TestSomethingThatUsessuggestions(t *testing.T) {
//
//		// make and configure a mocked suggestions
//		mockedsuggestions := &MoqSuggestions{
//			CreateFunc: func(context1 context.Context, createTopicSuggestionInput repository.CreateTopicSuggestionInput) (repository.TopicSuggestion, bool, error) {
//				panic("mock out the Create method")
//			},
//		}
//
//		// use mockedsuggestions in code that requires suggestions
//		// and then make assertions.
//
//	}
type MoqSuggestions struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(context1 context.Context, createTopicSuggestionInput repository.CreateTopicSuggestionInput) (repository.TopicSuggestion, bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// CreateTopicSuggestionInput is the createTopicSuggestionInput argument value.
			CreateTopicSuggestionInput repository.CreateTopicSuggestionInput
		}
	}
	lockCreate sync.RWMutex
}

// Create calls CreateFunc.
func (mock *MoqSuggestions) Create(context1 context.Context, createTopicSuggestionInput repository.CreateTopicSuggestionInput) (repository.TopicSuggestion, bool, error) {
	callInfo := struct {
		Context1                   context.Context
		CreateTopicSuggestionInput repository.CreateTopicSuggestionInput
	}{
		Context1:                   context1,
		CreateTopicSuggestionInput: createTopicSuggestionInput,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	if mock.CreateFunc == nil {
		var (
			topicSuggestion repository.TopicSuggestion
			b               bool
			err             error
		)
		return topicSuggestion, b, err
	}
	return mock.CreateFunc(context1, createTopicSuggestionInput)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedsuggestions.CreateCalls())
func (mock *MoqSuggestions) CreateCalls() []struct {
	Context1                   context.Context
	CreateTopicSuggestionInput repository.CreateTopicSuggestionInput
} {
	var calls []struct {
		Context1                   context.Context
		CreateTopicSuggestionInput repository.CreateTopicSuggestionInput
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}
