// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package app

import (
	"context"
	"sync"

	"github.com/go-telegram/bot/models"
)

// Ensure that MoqTelegramRunner does implement telegramRunner.
// If this is not the case, regenerate this file with mockery.
var _ telegramRunner = &MoqTelegramRunner{}

// MoqTelegramRunner is a mock implementation of telegramRunner.
//
//	func TestSomethingThatUsestelegramRunner(t *testing.T) {
//
//		// make and configure a mocked telegramRunner
//		mockedtelegramRunner := &MoqTelegramRunner{
//			AnswerCallbackFunc: func(context1 context.Context, s string, s1 string) error {
//				panic("mock out the AnswerCallback method")
//			},
//			EditPhotoFunc: func(context1 context.Context, n int64, n1 int, s string, s1 string, inlineKeyboardMarkup *models.InlineKeyboardMarkup) error {
//				panic("mock out the EditPhoto method")
//			},
//			EnsureIdentityFunc: func(context1 context.Context) error {
//				panic("mock out the EnsureIdentity method")
//			},
//			PinFunc: func(context1 context.Context, n int64, n1 int) error {
//				panic("mock out the Pin method")
//			},
//			RunFunc: func(context1 context.Context) error {
//				panic("mock out the Run method")
//			},
//			SendMarkdownFunc: func(context1 context.Context, n int64, s string) (int, error) {
//				panic("mock out the SendMarkdown method")
//			},
//			SendMarkdownPhotoFunc: func(context1 context.Context, n int64, s string, s1 string) (int, error) {
//				panic("mock out the SendMarkdownPhoto method")
//			},
//			SendMarkdownPhotoGroupFunc: func(context1 context.Context, n int64, strings []string, strings1 []string) (int, error) {
//				panic("mock out the SendMarkdownPhotoGroup method")
//			},
//			SendPhotoFunc: func(context1 context.Context, n int64, s string, s1 string, inlineKeyboardMarkup *models.InlineKeyboardMarkup) (int, error) {
//				panic("mock out the SendPhoto method")
//			},
//			SendTextFunc: func(context1 context.Context, n int64, s string) (int, error) {
//				panic("mock out the SendText method")
//			},
//			SendTextReplyFunc: func(context1 context.Context, n int64, s string, n1 int) (int, error) {
//				panic("mock out the SendTextReply method")
//			},
//			UsernameFunc: func() string {
//				panic("mock out the Username method")
//			},
//		}
//
//		// use mockedtelegramRunner in code that requires telegramRunner
//		// and then make assertions.
//
//	}
type MoqTelegramRunner struct {
	// AnswerCallbackFunc mocks the AnswerCallback method.
	AnswerCallbackFunc func(context1 context.Context, s string, s1 string) error

	// EditPhotoFunc mocks the EditPhoto method.
	EditPhotoFunc func(context1 context.Context, n int64, n1 int, s string, s1 string, inlineKeyboardMarkup *models.InlineKeyboardMarkup) error

	// EnsureIdentityFunc mocks the EnsureIdentity method.
	EnsureIdentityFunc func(context1 context.Context) error

	// PinFunc mocks the Pin method.
	PinFunc func(context1 context.Context, n int64, n1 int) error

	// RunFunc mocks the Run method.
	RunFunc func(context1 context.Context) error

	// SendMarkdownFunc mocks the SendMarkdown method.
	SendMarkdownFunc func(context1 context.Context, n int64, s string) (int, error)

	// SendMarkdownPhotoFunc mocks the SendMarkdownPhoto method.
	SendMarkdownPhotoFunc func(context1 context.Context, n int64, s string, s1 string) (int, error)

	// SendMarkdownPhotoGroupFunc mocks the SendMarkdownPhotoGroup method.
	SendMarkdownPhotoGroupFunc func(context1 context.Context, n int64, strings []string, strings1 []string) (int, error)

	// SendPhotoFunc mocks the SendPhoto method.
	SendPhotoFunc func(context1 context.Context, n int64, s string, s1 string, inlineKeyboardMarkup *models.InlineKeyboardMarkup) (int, error)

	// SendTextFunc mocks the SendText method.
	SendTextFunc func(context1 context.Context, n int64, s string) (int, error)

	// SendTextReplyFunc mocks the SendTextReply method.
	SendTextReplyFunc func(context1 context.Context, n int64, s string, n1 int) (int, error)

	// UsernameFunc mocks the Username method.
	UsernameFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// AnswerCallback holds details about calls to the AnswerCallback method.
		AnswerCallback []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
			// S1 is the s1 argument value.
			S1 string
		}
		// EditPhoto holds details about calls to the EditPhoto method.
		EditPhoto []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// N1 is the n1 argument value.
			N1 int
			// S is the s argument value.
			S string
			// S1 is the s1 argument value.
			S1 string
			// InlineKeyboardMarkup is the inlineKeyboardMarkup argument value.
			InlineKeyboardMarkup *models.InlineKeyboardMarkup
		}
		// EnsureIdentity holds details about calls to the EnsureIdentity method.
		EnsureIdentity []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
		}
		// Pin holds details about calls to the Pin method.
		Pin []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// N1 is the n1 argument value.
			N1 int
		}
		// Run holds details about calls to the Run method.
		Run []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
		}
		// SendMarkdown holds details about calls to the SendMarkdown method.
		SendMarkdown []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// S is the s argument value.
			S string
		}
		// SendMarkdownPhoto holds details about calls to the SendMarkdownPhoto method.
		SendMarkdownPhoto []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// S is the s argument value.
			S string
			// S1 is the s1 argument value.
			S1 string
		}
		// SendMarkdownPhotoGroup holds details about calls to the SendMarkdownPhotoGroup method.
		SendMarkdownPhotoGroup []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// Strings is the strings argument value.
			Strings []string
			// Strings1 is the strings1 argument value.
			Strings1 []string
		}
		// SendPhoto holds details about calls to the SendPhoto method.
		SendPhoto []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// S is the s argument value.
			S string
			// S1 is the s1 argument value.
			S1 string
			// InlineKeyboardMarkup is the inlineKeyboardMarkup argument value.
			InlineKeyboardMarkup *models.InlineKeyboardMarkup
		}
		// SendText holds details about calls to the SendText method.
		SendText []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// S is the s argument value.
			S string
		}
		// SendTextReply holds details about calls to the SendTextReply method.
		SendTextReply []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// S is the s argument value.
			S string
			// N1 is the n1 argument value.
			N1 int
		}
		// Username holds details about calls to the Username method.
		Username []struct {
		}
	}
	lockAnswerCallback         sync.RWMutex
	lockEditPhoto              sync.RWMutex
	lockEnsureIdentity         sync.RWMutex
	lockPin                    sync.RWMutex
	lockRun                    sync.RWMutex
	lockSendMarkdown           sync.RWMutex
	lockSendMarkdownPhoto      sync.RWMutex
	lockSendMarkdownPhotoGroup sync.RWMutex
	lockSendPhoto              sync.RWMutex
	lockSendText               sync.RWMutex
	lockSendTextReply          sync.RWMutex
	lockUsername               sync.RWMutex
}

// AnswerCallback calls AnswerCallbackFunc.
func (mock *MoqTelegramRunner) AnswerCallback(context1 context.Context, s string, s1 string) error {
	callInfo := struct {
		Context1 context.Context
		S        string
		S1       string
	}{
		Context1: context1,
		S:        s,
		S1:       s1,
	}
	mock.lockAnswerCallback.Lock()
	mock.calls.AnswerCallback = append(mock.calls.AnswerCallback, callInfo)
	mock.lockAnswerCallback.Unlock()
	if mock.AnswerCallbackFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.AnswerCallbackFunc(context1, s, s1)
}

// AnswerCallbackCalls gets all the calls that were made to AnswerCallback.
// Check the length with:
//
//	len(mockedtelegramRunner.AnswerCallbackCalls())
func (mock *MoqTelegramRunner) AnswerCallbackCalls() []struct {
	Context1 context.Context
	S        string
	S1       string
} {
	var calls []struct {
		Context1 context.Context
		S        string
		S1       string
	}
	mock.lockAnswerCallback.RLock()
	calls = mock.calls.AnswerCallback
	mock.lockAnswerCallback.RUnlock()
	return calls
}

// EditPhoto calls EditPhotoFunc.
func (mock *MoqTelegramRunner) EditPhoto(context1 context.Context, n int64, n1 int, s string, s1 string, inlineKeyboardMarkup *models.InlineKeyboardMarkup) error {
	callInfo := struct {
		Context1             context.Context
		N                    int64
		N1                   int
		S                    string
		S1                   string
		InlineKeyboardMarkup *models.InlineKeyboardMarkup
	}{
		Context1:             context1,
		N:                    n,
		N1:                   n1,
		S:                    s,
		S1:                   s1,
		InlineKeyboardMarkup: inlineKeyboardMarkup,
	}
	mock.lockEditPhoto.Lock()
	mock.calls.EditPhoto = append(mock.calls.EditPhoto, callInfo)
	mock.lockEditPhoto.Unlock()
	if mock.EditPhotoFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.EditPhotoFunc(context1, n, n1, s, s1, inlineKeyboardMarkup)
}

// EditPhotoCalls gets all the calls that were made to EditPhoto.
// Check the length with:
//
//	len(mockedtelegramRunner.EditPhotoCalls())
func (mock *MoqTelegramRunner) EditPhotoCalls() []struct {
	Context1             context.Context
	N                    int64
	N1                   int
	S                    string
	S1                   string
	InlineKeyboardMarkup *models.InlineKeyboardMarkup
} {
	var calls []struct {
		Context1             context.Context
		N                    int64
		N1                   int
		S                    string
		S1                   string
		InlineKeyboardMarkup *models.InlineKeyboardMarkup
	}
	mock.lockEditPhoto.RLock()
	calls = mock.calls.EditPhoto
	mock.lockEditPhoto.RUnlock()
	return calls
}

// EnsureIdentity calls EnsureIdentityFunc.
func (mock *MoqTelegramRunner) EnsureIdentity(context1 context.Context) error {
	callInfo := struct {
		Context1 context.Context
	}{
		Context1: context1,
	}
	mock.lockEnsureIdentity.Lock()
	mock.calls.EnsureIdentity = append(mock.calls.EnsureIdentity, callInfo)
	mock.lockEnsureIdentity.Unlock()
	if mock.EnsureIdentityFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.EnsureIdentityFunc(context1)
}

// EnsureIdentityCalls gets all the calls that were made to EnsureIdentity.
// Check the length with:
//
//	len(mockedtelegramRunner.EnsureIdentityCalls())
func (mock *MoqTelegramRunner) EnsureIdentityCalls() []struct {
	Context1 context.Context
} {
	var calls []struct {
		Context1 context.Context
	}
	mock.lockEnsureIdentity.RLock()
	calls = mock.calls.EnsureIdentity
	mock.lockEnsureIdentity.RUnlock()
	return calls
}

// Pin calls PinFunc.
func (mock *MoqTelegramRunner) Pin(context1 context.Context, n int64, n1 int) error {
	callInfo := struct {
		Context1 context.Context
		N        int64
		N1       int
	}{
		Context1: context1,
		N:        n,
		N1:       n1,
	}
	mock.lockPin.Lock()
	mock.calls.Pin = append(mock.calls.Pin, callInfo)
	mock.lockPin.Unlock()
	if mock.PinFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.PinFunc(context1, n, n1)
}

// PinCalls gets all the calls that were made to Pin.
// Check the length with:
//
//	len(mockedtelegramRunner.PinCalls())
func (mock *MoqTelegramRunner) PinCalls() []struct {
	Context1 context.Context
	N        int64
	N1       int
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		N1       int
	}
	mock.lockPin.RLock()
	calls = mock.calls.Pin
	mock.lockPin.RUnlock()
	return calls
}

// Run calls RunFunc.
func (mock *MoqTelegramRunner) Run(context1 context.Context) error {
	callInfo := struct {
		Context1 context.Context
	}{
		Context1: context1,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	if mock.RunFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.RunFunc(context1)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedtelegramRunner.RunCalls())
func (mock *MoqTelegramRunner) RunCalls() []struct {
	Context1 context.Context
} {
	var calls []struct {
		Context1 context.Context
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}

// SendMarkdown calls SendMarkdownFunc.
func (mock *MoqTelegramRunner) SendMarkdown(context1 context.Context, n int64, s string) (int, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		S        string
	}{
		Context1: context1,
		N:        n,
		S:        s,
	}
	mock.lockSendMarkdown.Lock()
	mock.calls.SendMarkdown = append(mock.calls.SendMarkdown, callInfo)
	mock.lockSendMarkdown.Unlock()
	if mock.SendMarkdownFunc == nil {
		var (
			n1  int
			err error
		)
		return n1, err
	}
	return mock.SendMarkdownFunc(context1, n, s)
}

// SendMarkdownCalls gets all the calls that were made to SendMarkdown.
// Check the length with:
//
//	len(mockedtelegramRunner.SendMarkdownCalls())
func (mock *MoqTelegramRunner) SendMarkdownCalls() []struct {
	Context1 context.Context
	N        int64
	S        string
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		S        string
	}
	mock.lockSendMarkdown.RLock()
	calls = mock.calls.SendMarkdown
	mock.lockSendMarkdown.RUnlock()
	return calls
}

// SendMarkdownPhoto calls SendMarkdownPhotoFunc.
func (mock *MoqTelegramRunner) SendMarkdownPhoto(context1 context.Context, n int64, s string, s1 string) (int, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		S        string
		S1       string
	}{
		Context1: context1,
		N:        n,
		S:        s,
		S1:       s1,
	}
	mock.lockSendMarkdownPhoto.Lock()
	mock.calls.SendMarkdownPhoto = append(mock.calls.SendMarkdownPhoto, callInfo)
	mock.lockSendMarkdownPhoto.Unlock()
	if mock.SendMarkdownPhotoFunc == nil {
		var (
			n1  int
			err error
		)
		return n1, err
	}
	return mock.SendMarkdownPhotoFunc(context1, n, s, s1)
}

// SendMarkdownPhotoCalls gets all the calls that were made to SendMarkdownPhoto.
// Check the length with:
//
//	len(mockedtelegramRunner.SendMarkdownPhotoCalls())
func (mock *MoqTelegramRunner) SendMarkdownPhotoCalls() []struct {
	Context1 context.Context
	N        int64
	S        string
	S1       string
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		S        string
		S1       string
	}
	mock.lockSendMarkdownPhoto.RLock()
	calls = mock.calls.SendMarkdownPhoto
	mock.lockSendMarkdownPhoto.RUnlock()
	return calls
}

// SendMarkdownPhotoGroup calls SendMarkdownPhotoGroupFunc.
func (mock *MoqTelegramRunner) SendMarkdownPhotoGroup(context1 context.Context, n int64, strings []string, strings1 []string) (int, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		Strings  []string
		Strings1 []string
	}{
		Context1: context1,
		N:        n,
		Strings:  strings,
		Strings1: strings1,
	}
	mock.lockSendMarkdownPhotoGroup.Lock()
	mock.calls.SendMarkdownPhotoGroup = append(mock.calls.SendMarkdownPhotoGroup, callInfo)
	mock.lockSendMarkdownPhotoGroup.Unlock()
	if mock.SendMarkdownPhotoGroupFunc == nil {
		var (
			n1  int
			err error
		)
		return n1, err
	}
	return mock.SendMarkdownPhotoGroupFunc(context1, n, strings, strings1)
}

// SendMarkdownPhotoGroupCalls gets all the calls that were made to SendMarkdownPhotoGroup.
// Check the length with:
//
//	len(mockedtelegramRunner.SendMarkdownPhotoGroupCalls())
func (mock *MoqTelegramRunner) SendMarkdownPhotoGroupCalls() []struct {
	Context1 context.Context
	N        int64
	Strings  []string
	Strings1 []string
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		Strings  []string
		Strings1 []string
	}
	mock.lockSendMarkdownPhotoGroup.RLock()
	calls = mock.calls.SendMarkdownPhotoGroup
	mock.lockSendMarkdownPhotoGroup.RUnlock()
	return calls
}

// SendPhoto calls SendPhotoFunc.
func (mock *MoqTelegramRunner) SendPhoto(context1 context.Context, n int64, s string, s1 string, inlineKeyboardMarkup *models.InlineKeyboardMarkup) (int, error) {
	callInfo := struct {
		Context1             context.Context
		N                    int64
		S                    string
		S1                   string
		InlineKeyboardMarkup *models.InlineKeyboardMarkup
	}{
		Context1:             context1,
		N:                    n,
		S:                    s,
		S1:                   s1,
		InlineKeyboardMarkup: inlineKeyboardMarkup,
	}
	mock.lockSendPhoto.Lock()
	mock.calls.SendPhoto = append(mock.calls.SendPhoto, callInfo)
	mock.lockSendPhoto.Unlock()
	if mock.SendPhotoFunc == nil {
		var (
			n1  int
			err error
		)
		return n1, err
	}
	return mock.SendPhotoFunc(context1, n, s, s1, inlineKeyboardMarkup)
}

// SendPhotoCalls gets all the calls that were made to SendPhoto.
// Check the length with:
//
//	len(mockedtelegramRunner.SendPhotoCalls())
func (mock *MoqTelegramRunner) SendPhotoCalls() []struct {
	Context1             context.Context
	N                    int64
	S                    string
	S1                   string
	InlineKeyboardMarkup *models.InlineKeyboardMarkup
} {
	var calls []struct {
		Context1             context.Context
		N                    int64
		S                    string
		S1                   string
		InlineKeyboardMarkup *models.InlineKeyboardMarkup
	}
	mock.lockSendPhoto.RLock()
	calls = mock.calls.SendPhoto
	mock.lockSendPhoto.RUnlock()
	return calls
}

// SendText calls SendTextFunc.
func (mock *MoqTelegramRunner) SendText(context1 context.Context, n int64, s string) (int, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		S        string
	}{
		Context1: context1,
		N:        n,
		S:        s,
	}
	mock.lockSendText.Lock()
	mock.calls.SendText = append(mock.calls.SendText, callInfo)
	mock.lockSendText.Unlock()
	if mock.SendTextFunc == nil {
		var (
			n1  int
			err error
		)
		return n1, err
	}
	return mock.SendTextFunc(context1, n, s)
}

// SendTextCalls gets all the calls that were made to SendText.
// Check the length with:
//
//	len(mockedtelegramRunner.SendTextCalls())
func (mock *MoqTelegramRunner) SendTextCalls() []struct {
	Context1 context.Context
	N        int64
	S        string
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		S        string
	}
	mock.lockSendText.RLock()
	calls = mock.calls.SendText
	mock.lockSendText.RUnlock()
	return calls
}

// SendTextReply calls SendTextReplyFunc.
func (mock *MoqTelegramRunner) SendTextReply(context1 context.Context, n int64, s string, n1 int) (int, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		S        string
		N1       int
	}{
		Context1: context1,
		N:        n,
		S:        s,
		N1:       n1,
	}
	mock.lockSendTextReply.Lock()
	mock.calls.SendTextReply = append(mock.calls.SendTextReply, callInfo)
	mock.lockSendTextReply.Unlock()
	if mock.SendTextReplyFunc == nil {
		var (
			n2  int
			err error
		)
		return n2, err
	}
	return mock.SendTextReplyFunc(context1, n, s, n1)
}

// SendTextReplyCalls gets all the calls that were made to SendTextReply.
// Check the length with:
//
//	len(mockedtelegramRunner.SendTextReplyCalls())
func (mock *MoqTelegramRunner) SendTextReplyCalls() []struct {
	Context1 context.Context
	N        int64
	S        string
	N1       int
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		S        string
		N1       int
	}
	mock.lockSendTextReply.RLock()
	calls = mock.calls.SendTextReply
	mock.lockSendTextReply.RUnlock()
	return calls
}

// Username calls UsernameFunc.
func (mock *MoqTelegramRunner) Username() string {
	callInfo := struct {
	}{}
	mock.lockUsername.Lock()
	mock.calls.Username = append(mock.calls.Username, callInfo)
	mock.lockUsername.Unlock()
	if mock.UsernameFunc == nil {
		var (
			s string
		)
		return s
	}
	return mock.UsernameFunc()
}

// UsernameCalls gets all the calls that were made to Username.
// Check the length with:
//
//	len(mockedtelegramRunner.UsernameCalls())
func (mock *MoqTelegramRunner) UsernameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockUsername.RLock()
	calls = mock.calls.Username
	mock.lockUsername.RUnlock()
	return calls
}
