// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package scheduler

import (
	"context"
	"sync"
	"time"

	"github.com/TiraelSedai/PhotoChallengeBot/internal/repository"
)

// Ensure that MoqChallenges does implement challenges.
// If this is not the case, regenerate this file with mockery.
var _ challenges = &MoqChallenges{}

// MoqChallenges is a mock implementation of challenges.
//
//	func TestSomethingThatUseschallenges(t *testing.T) {
//
//		// make and configure a mocked challenges
//		mockedchallenges := &MoqChallenges{
//			ClaimReminderFunc: func(context1 context.Context, n int64, time1 time.Time) (bool, error) {
//				panic("mock out the ClaimReminder method")
//			},
//			ClaimVoteStartFunc: func(context1 context.Context, n int64, time1 time.Time) (bool, error) {
//				panic("mock out the ClaimVoteStart method")
//			},
//			ExtendVoteUntilFunc: func(context1 context.Context, n int64, time1 time.Time) (*time.Time, error) {
//				panic("mock out the ExtendVoteUntil method")
//			},
//			FinishVotingFunc: func(context1 context.Context, n int64, time1 time.Time) (bool, error) {
//				panic("mock out the FinishVoting method")
//			},
//			ListDueAcceptanceClosuresFunc: func(context1 context.Context, n int64, time1 time.Time, n1 int) ([]repository.Challenge, error) {
//				panic("mock out the ListDueAcceptanceClosures method")
//			},
//			ListDueRemindersFunc: func(context1 context.Context, n int64, time1 time.Time, n1 int) ([]repository.Challenge, error) {
//				panic("mock out the ListDueReminders method")
//			},
//			ListDueVotingClosuresFunc: func(context1 context.Context, n int64, time1 time.Time, n1 int) ([]repository.Challenge, error) {
//				panic("mock out the ListDueVotingClosures method")
//			},
//			ListUnpublishedVoteStartsFunc: func(context1 context.Context, n int64, n1 int) ([]repository.Challenge, error) {
//				panic("mock out the ListUnpublishedVoteStarts method")
//			},
//			MarkReminderSentFunc: func(context1 context.Context, n int64, n1 int, time1 time.Time, time11 time.Time) (bool, error) {
//				panic("mock out the MarkReminderSent method")
//			},
//			MarkVoteStartPinnedFunc: func(context1 context.Context, n int64, time1 time.Time, time11 time.Time) (bool, error) {
//				panic("mock out the MarkVoteStartPinned method")
//			},
//			RecordVoteMessageIDFunc: func(context1 context.Context, n int64, n1 int, time1 time.Time) (bool, error) {
//				panic("mock out the RecordVoteMessageID method")
//			},
//			ReleaseReminderClaimFunc: func(context1 context.Context, n int64, time1 time.Time) error {
//				panic("mock out the ReleaseReminderClaim method")
//			},
//			ReleaseVoteStartClaimFunc: func(context1 context.Context, n int64, time1 time.Time) error {
//				panic("mock out the ReleaseVoteStartClaim method")
//			},
//			SetVoteMessageIDFunc: func(context1 context.Context, n int64, n1 int, time1 time.Time, time11 time.Time) (bool, error) {
//				panic("mock out the SetVoteMessageID method")
//			},
//			StartVotingFunc: func(context1 context.Context, n int64, time1 time.Time) (bool, error) {
//				panic("mock out the StartVoting method")
//			},
//		}
//
//		// use mockedchallenges in code that requires challenges
//		// and then make assertions.
//
//	}
type MoqChallenges struct {
	// ClaimReminderFunc mocks the ClaimReminder method.
	ClaimReminderFunc func(context1 context.Context, n int64, time1 time.Time) (bool, error)

	// ClaimVoteStartFunc mocks the ClaimVoteStart method.
	ClaimVoteStartFunc func(context1 context.Context, n int64, time1 time.Time) (bool, error)

	// ExtendVoteUntilFunc mocks the ExtendVoteUntil method.
	ExtendVoteUntilFunc func(context1 context.Context, n int64, time1 time.Time) (*time.Time, error)

	// FinishVotingFunc mocks the FinishVoting method.
	FinishVotingFunc func(context1 context.Context, n int64, time1 time.Time) (bool, error)

	// ListDueAcceptanceClosuresFunc mocks the ListDueAcceptanceClosures method.
	ListDueAcceptanceClosuresFunc func(context1 context.Context, n int64, time1 time.Time, n1 int) ([]repository.Challenge, error)

	// ListDueRemindersFunc mocks the ListDueReminders method.
	ListDueRemindersFunc func(context1 context.Context, n int64, time1 time.Time, n1 int) ([]repository.Challenge, error)

	// ListDueVotingClosuresFunc mocks the ListDueVotingClosures method.
	ListDueVotingClosuresFunc func(context1 context.Context, n int64, time1 time.Time, n1 int) ([]repository.Challenge, error)

	// ListUnpublishedVoteStartsFunc mocks the ListUnpublishedVoteStarts method.
	ListUnpublishedVoteStartsFunc func(context1 context.Context, n int64, n1 int) ([]repository.Challenge, error)

	// MarkReminderSentFunc mocks the MarkReminderSent method.
	MarkReminderSentFunc func(context1 context.Context, n int64, n1 int, time1 time.Time, time11 time.Time) (bool, error)

	// MarkVoteStartPinnedFunc mocks the MarkVoteStartPinned method.
	MarkVoteStartPinnedFunc func(context1 context.Context, n int64, time1 time.Time, time11 time.Time) (bool, error)

	// RecordVoteMessageIDFunc mocks the RecordVoteMessageID method.
	RecordVoteMessageIDFunc func(context1 context.Context, n int64, n1 int, time1 time.Time) (bool, error)

	// ReleaseReminderClaimFunc mocks the ReleaseReminderClaim method.
	ReleaseReminderClaimFunc func(context1 context.Context, n int64, time1 time.Time) error

	// ReleaseVoteStartClaimFunc mocks the ReleaseVoteStartClaim method.
	ReleaseVoteStartClaimFunc func(context1 context.Context, n int64, time1 time.Time) error

	// SetVoteMessageIDFunc mocks the SetVoteMessageID method.
	SetVoteMessageIDFunc func(context1 context.Context, n int64, n1 int, time1 time.Time, time11 time.Time) (bool, error)

	// StartVotingFunc mocks the StartVoting method.
	StartVotingFunc func(context1 context.Context, n int64, time1 time.Time) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// ClaimReminder holds details about calls to the ClaimReminder method.
		ClaimReminder []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// Time1 is the time1 argument value.
			Time1 time.Time
		}
		// ClaimVoteStart holds details about calls to the ClaimVoteStart method.
		ClaimVoteStart []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// Time1 is the time1 argument value.
			Time1 time.Time
		}
		// ExtendVoteUntil holds details about calls to the ExtendVoteUntil method.
		ExtendVoteUntil []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// Time1 is the time1 argument value.
			Time1 time.Time
		}
		// FinishVoting holds details about calls to the FinishVoting method.
		FinishVoting []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// Time1 is the time1 argument value.
			Time1 time.Time
		}
		// ListDueAcceptanceClosures holds details about calls to the ListDueAcceptanceClosures method.
		ListDueAcceptanceClosures []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// Time1 is the time1 argument value.
			Time1 time.Time
			// N1 is the n1 argument value.
			N1 int
		}
		// ListDueReminders holds details about calls to the ListDueReminders method.
		ListDueReminders []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// Time1 is the time1 argument value.
			Time1 time.Time
			// N1 is the n1 argument value.
			N1 int
		}
		// ListDueVotingClosures holds details about calls to the ListDueVotingClosures method.
		ListDueVotingClosures []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// Time1 is the time1 argument value.
			Time1 time.Time
			// N1 is the n1 argument value.
			N1 int
		}
		// ListUnpublishedVoteStarts holds details about calls to the ListUnpublishedVoteStarts method.
		ListUnpublishedVoteStarts []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// N1 is the n1 argument value.
			N1 int
		}
		// MarkReminderSent holds details about calls to the MarkReminderSent method.
		MarkReminderSent []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// N1 is the n1 argument value.
			N1 int
			// Time1 is the time1 argument value.
			Time1 time.Time
			// Time11 is the time11 argument value.
			Time11 time.Time
		}
		// MarkVoteStartPinned holds details about calls to the MarkVoteStartPinned method.
		MarkVoteStartPinned []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// Time1 is the time1 argument value.
			Time1 time.Time
			// Time11 is the time11 argument value.
			Time11 time.Time
		}
		// RecordVoteMessageID holds details about calls to the RecordVoteMessageID method.
		RecordVoteMessageID []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// N1 is the n1 argument value.
			N1 int
			// Time1 is the time1 argument value.
			Time1 time.Time
		}
		// ReleaseReminderClaim holds details about calls to the ReleaseReminderClaim method.
		ReleaseReminderClaim []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// Time1 is the time1 argument value.
			Time1 time.Time
		}
		// ReleaseVoteStartClaim holds details about calls to the ReleaseVoteStartClaim method.
		ReleaseVoteStartClaim []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// Time1 is the time1 argument value.
			Time1 time.Time
		}
		// SetVoteMessageID holds details about calls to the SetVoteMessageID method.
		SetVoteMessageID []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// N1 is the n1 argument value.
			N1 int
			// Time1 is the time1 argument value.
			Time1 time.Time
			// Time11 is the time11 argument value.
			Time11 time.Time
		}
		// StartVoting holds details about calls to the StartVoting method.
		StartVoting []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// Time1 is the time1 argument value.
			Time1 time.Time
		}
	}
	lockClaimReminder             sync.RWMutex
	lockClaimVoteStart            sync.RWMutex
	lockExtendVoteUntil           sync.RWMutex
	lockFinishVoting              sync.RWMutex
	lockListDueAcceptanceClosures sync.RWMutex
	lockListDueReminders          sync.RWMutex
	lockListDueVotingClosures     sync.RWMutex
	lockListUnpublishedVoteStarts sync.RWMutex
	lockMarkReminderSent          sync.RWMutex
	lockMarkVoteStartPinned       sync.RWMutex
	lockRecordVoteMessageID       sync.RWMutex
	lockReleaseReminderClaim      sync.RWMutex
	lockReleaseVoteStartClaim     sync.RWMutex
	lockSetVoteMessageID          sync.RWMutex
	lockStartVoting               sync.RWMutex
}

// ClaimReminder calls ClaimReminderFunc.
func (mock *MoqChallenges) ClaimReminder(context1 context.Context, n int64, time1 time.Time) (bool, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
	}{
		Context1: context1,
		N:        n,
		Time1:    time1,
	}
	mock.lockClaimReminder.Lock()
	mock.calls.ClaimReminder = append(mock.calls.ClaimReminder, callInfo)
	mock.lockClaimReminder.Unlock()
	if mock.ClaimReminderFunc == nil {
		var (
			b   bool
			err error
		)
		return b, err
	}
	return mock.ClaimReminderFunc(context1, n, time1)
}

// ClaimReminderCalls gets all the calls that were made to ClaimReminder.
// Check the length with:
//
//	len(mockedchallenges.ClaimReminderCalls())
func (mock *MoqChallenges) ClaimReminderCalls() []struct {
	Context1 context.Context
	N        int64
	Time1    time.Time
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
	}
	mock.lockClaimReminder.RLock()
	calls = mock.calls.ClaimReminder
	mock.lockClaimReminder.RUnlock()
	return calls
}

// ClaimVoteStart calls ClaimVoteStartFunc.
func (mock *MoqChallenges) ClaimVoteStart(context1 context.Context, n int64, time1 time.Time) (bool, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
	}{
		Context1: context1,
		N:        n,
		Time1:    time1,
	}
	mock.lockClaimVoteStart.Lock()
	mock.calls.ClaimVoteStart = append(mock.calls.ClaimVoteStart, callInfo)
	mock.lockClaimVoteStart.Unlock()
	if mock.ClaimVoteStartFunc == nil {
		var (
			b   bool
			err error
		)
		return b, err
	}
	return mock.ClaimVoteStartFunc(context1, n, time1)
}

// ClaimVoteStartCalls gets all the calls that were made to ClaimVoteStart.
// Check the length with:
//
//	len(mockedchallenges.ClaimVoteStartCalls())
func (mock *MoqChallenges) ClaimVoteStartCalls() []struct {
	Context1 context.Context
	N        int64
	Time1    time.Time
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
	}
	mock.lockClaimVoteStart.RLock()
	calls = mock.calls.ClaimVoteStart
	mock.lockClaimVoteStart.RUnlock()
	return calls
}

// ExtendVoteUntil calls ExtendVoteUntilFunc.
func (mock *MoqChallenges) ExtendVoteUntil(context1 context.Context, n int64, time1 time.Time) (*time.Time, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
	}{
		Context1: context1,
		N:        n,
		Time1:    time1,
	}
	mock.lockExtendVoteUntil.Lock()
	mock.calls.ExtendVoteUntil = append(mock.calls.ExtendVoteUntil, callInfo)
	mock.lockExtendVoteUntil.Unlock()
	if mock.ExtendVoteUntilFunc == nil {
		var (
			time11 *time.Time
			err    error
		)
		return time11, err
	}
	return mock.ExtendVoteUntilFunc(context1, n, time1)
}

// ExtendVoteUntilCalls gets all the calls that were made to ExtendVoteUntil.
// Check the length with:
//
//	len(mockedchallenges.ExtendVoteUntilCalls())
func (mock *MoqChallenges) ExtendVoteUntilCalls() []struct {
	Context1 context.Context
	N        int64
	Time1    time.Time
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
	}
	mock.lockExtendVoteUntil.RLock()
	calls = mock.calls.ExtendVoteUntil
	mock.lockExtendVoteUntil.RUnlock()
	return calls
}

// FinishVoting calls FinishVotingFunc.
func (mock *MoqChallenges) FinishVoting(context1 context.Context, n int64, time1 time.Time) (bool, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
	}{
		Context1: context1,
		N:        n,
		Time1:    time1,
	}
	mock.lockFinishVoting.Lock()
	mock.calls.FinishVoting = append(mock.calls.FinishVoting, callInfo)
	mock.lockFinishVoting.Unlock()
	if mock.FinishVotingFunc == nil {
		var (
			b   bool
			err error
		)
		return b, err
	}
	return mock.FinishVotingFunc(context1, n, time1)
}

// FinishVotingCalls gets all the calls that were made to FinishVoting.
// Check the length with:
//
//	len(mockedchallenges.FinishVotingCalls())
func (mock *MoqChallenges) FinishVotingCalls() []struct {
	Context1 context.Context
	N        int64
	Time1    time.Time
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
	}
	mock.lockFinishVoting.RLock()
	calls = mock.calls.FinishVoting
	mock.lockFinishVoting.RUnlock()
	return calls
}

// ListDueAcceptanceClosures calls ListDueAcceptanceClosuresFunc.
func (mock *MoqChallenges) ListDueAcceptanceClosures(context1 context.Context, n int64, time1 time.Time, n1 int) ([]repository.Challenge, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
		N1       int
	}{
		Context1: context1,
		N:        n,
		Time1:    time1,
		N1:       n1,
	}
	mock.lockListDueAcceptanceClosures.Lock()
	mock.calls.ListDueAcceptanceClosures = append(mock.calls.ListDueAcceptanceClosures, callInfo)
	mock.lockListDueAcceptanceClosures.Unlock()
	if mock.ListDueAcceptanceClosuresFunc == nil {
		var (
			challenges []repository.Challenge
			err        error
		)
		return challenges, err
	}
	return mock.ListDueAcceptanceClosuresFunc(context1, n, time1, n1)
}

// ListDueAcceptanceClosuresCalls gets all the calls that were made to ListDueAcceptanceClosures.
// Check the length with:
//
//	len(mockedchallenges.ListDueAcceptanceClosuresCalls())
func (mock *MoqChallenges) ListDueAcceptanceClosuresCalls() []struct {
	Context1 context.Context
	N        int64
	Time1    time.Time
	N1       int
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
		N1       int
	}
	mock.lockListDueAcceptanceClosures.RLock()
	calls = mock.calls.ListDueAcceptanceClosures
	mock.lockListDueAcceptanceClosures.RUnlock()
	return calls
}

// ListDueReminders calls ListDueRemindersFunc.
func (mock *MoqChallenges) ListDueReminders(context1 context.Context, n int64, time1 time.Time, n1 int) ([]repository.Challenge, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
		N1       int
	}{
		Context1: context1,
		N:        n,
		Time1:    time1,
		N1:       n1,
	}
	mock.lockListDueReminders.Lock()
	mock.calls.ListDueReminders = append(mock.calls.ListDueReminders, callInfo)
	mock.lockListDueReminders.Unlock()
	if mock.ListDueRemindersFunc == nil {
		var (
			challenges []repository.Challenge
			err        error
		)
		return challenges, err
	}
	return mock.ListDueRemindersFunc(context1, n, time1, n1)
}

// ListDueRemindersCalls gets all the calls that were made to ListDueReminders.
// Check the length with:
//
//	len(mockedchallenges.ListDueRemindersCalls())
func (mock *MoqChallenges) ListDueRemindersCalls() []struct {
	Context1 context.Context
	N        int64
	Time1    time.Time
	N1       int
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
		N1       int
	}
	mock.lockListDueReminders.RLock()
	calls = mock.calls.ListDueReminders
	mock.lockListDueReminders.RUnlock()
	return calls
}

// ListDueVotingClosures calls ListDueVotingClosuresFunc.
func (mock *MoqChallenges) ListDueVotingClosures(context1 context.Context, n int64, time1 time.Time, n1 int) ([]repository.Challenge, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
		N1       int
	}{
		Context1: context1,
		N:        n,
		Time1:    time1,
		N1:       n1,
	}
	mock.lockListDueVotingClosures.Lock()
	mock.calls.ListDueVotingClosures = append(mock.calls.ListDueVotingClosures, callInfo)
	mock.lockListDueVotingClosures.Unlock()
	if mock.ListDueVotingClosuresFunc == nil {
		var (
			challenges []repository.Challenge
			err        error
		)
		return challenges, err
	}
	return mock.ListDueVotingClosuresFunc(context1, n, time1, n1)
}

// ListDueVotingClosuresCalls gets all the calls that were made to ListDueVotingClosures.
// Check the length with:
//
//	len(mockedchallenges.ListDueVotingClosuresCalls())
func (mock *MoqChallenges) ListDueVotingClosuresCalls() []struct {
	Context1 context.Context
	N        int64
	Time1    time.Time
	N1       int
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
		N1       int
	}
	mock.lockListDueVotingClosures.RLock()
	calls = mock.calls.ListDueVotingClosures
	mock.lockListDueVotingClosures.RUnlock()
	return calls
}

// ListUnpublishedVoteStarts calls ListUnpublishedVoteStartsFunc.
func (mock *MoqChallenges) ListUnpublishedVoteStarts(context1 context.Context, n int64, n1 int) ([]repository.Challenge, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		N1       int
	}{
		Context1: context1,
		N:        n,
		N1:       n1,
	}
	mock.lockListUnpublishedVoteStarts.Lock()
	mock.calls.ListUnpublishedVoteStarts = append(mock.calls.ListUnpublishedVoteStarts, callInfo)
	mock.lockListUnpublishedVoteStarts.Unlock()
	if mock.ListUnpublishedVoteStartsFunc == nil {
		var (
			challenges []repository.Challenge
			err        error
		)
		return challenges, err
	}
	return mock.ListUnpublishedVoteStartsFunc(context1, n, n1)
}

// ListUnpublishedVoteStartsCalls gets all the calls that were made to ListUnpublishedVoteStarts.
// Check the length with:
//
//	len(mockedchallenges.ListUnpublishedVoteStartsCalls())
func (mock *MoqChallenges) ListUnpublishedVoteStartsCalls() []struct {
	Context1 context.Context
	N        int64
	N1       int
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		N1       int
	}
	mock.lockListUnpublishedVoteStarts.RLock()
	calls = mock.calls.ListUnpublishedVoteStarts
	mock.lockListUnpublishedVoteStarts.RUnlock()
	return calls
}

// MarkReminderSent calls MarkReminderSentFunc.
func (mock *MoqChallenges) MarkReminderSent(context1 context.Context, n int64, n1 int, time1 time.Time, time11 time.Time) (bool, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		N1       int
		Time1    time.Time
		Time11   time.Time
	}{
		Context1: context1,
		N:        n,
		N1:       n1,
		Time1:    time1,
		Time11:   time11,
	}
	mock.lockMarkReminderSent.Lock()
	mock.calls.MarkReminderSent = append(mock.calls.MarkReminderSent, callInfo)
	mock.lockMarkReminderSent.Unlock()
	if mock.MarkReminderSentFunc == nil {
		var (
			b   bool
			err error
		)
		return b, err
	}
	return mock.MarkReminderSentFunc(context1, n, n1, time1, time11)
}

// MarkReminderSentCalls gets all the calls that were made to MarkReminderSent.
// Check the length with:
//
//	len(mockedchallenges.MarkReminderSentCalls())
func (mock *MoqChallenges) MarkReminderSentCalls() []struct {
	Context1 context.Context
	N        int64
	N1       int
	Time1    time.Time
	Time11   time.Time
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		N1       int
		Time1    time.Time
		Time11   time.Time
	}
	mock.lockMarkReminderSent.RLock()
	calls = mock.calls.MarkReminderSent
	mock.lockMarkReminderSent.RUnlock()
	return calls
}

// MarkVoteStartPinned calls MarkVoteStartPinnedFunc.
func (mock *MoqChallenges) MarkVoteStartPinned(context1 context.Context, n int64, time1 time.Time, time11 time.Time) (bool, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
		Time11   time.Time
	}{
		Context1: context1,
		N:        n,
		Time1:    time1,
		Time11:   time11,
	}
	mock.lockMarkVoteStartPinned.Lock()
	mock.calls.MarkVoteStartPinned = append(mock.calls.MarkVoteStartPinned, callInfo)
	mock.lockMarkVoteStartPinned.Unlock()
	if mock.MarkVoteStartPinnedFunc == nil {
		var (
			b   bool
			err error
		)
		return b, err
	}
	return mock.MarkVoteStartPinnedFunc(context1, n, time1, time11)
}

// MarkVoteStartPinnedCalls gets all the calls that were made to MarkVoteStartPinned.
// Check the length with:
//
//	len(mockedchallenges.MarkVoteStartPinnedCalls())
func (mock *MoqChallenges) MarkVoteStartPinnedCalls() []struct {
	Context1 context.Context
	N        int64
	Time1    time.Time
	Time11   time.Time
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
		Time11   time.Time
	}
	mock.lockMarkVoteStartPinned.RLock()
	calls = mock.calls.MarkVoteStartPinned
	mock.lockMarkVoteStartPinned.RUnlock()
	return calls
}

// RecordVoteMessageID calls RecordVoteMessageIDFunc.
func (mock *MoqChallenges) RecordVoteMessageID(context1 context.Context, n int64, n1 int, time1 time.Time) (bool, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		N1       int
		Time1    time.Time
	}{
		Context1: context1,
		N:        n,
		N1:       n1,
		Time1:    time1,
	}
	mock.lockRecordVoteMessageID.Lock()
	mock.calls.RecordVoteMessageID = append(mock.calls.RecordVoteMessageID, callInfo)
	mock.lockRecordVoteMessageID.Unlock()
	if mock.RecordVoteMessageIDFunc == nil {
		var (
			b   bool
			err error
		)
		return b, err
	}
	return mock.RecordVoteMessageIDFunc(context1, n, n1, time1)
}

// RecordVoteMessageIDCalls gets all the calls that were made to RecordVoteMessageID.
// Check the length with:
//
//	len(mockedchallenges.RecordVoteMessageIDCalls())
func (mock *MoqChallenges) RecordVoteMessageIDCalls() []struct {
	Context1 context.Context
	N        int64
	N1       int
	Time1    time.Time
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		N1       int
		Time1    time.Time
	}
	mock.lockRecordVoteMessageID.RLock()
	calls = mock.calls.RecordVoteMessageID
	mock.lockRecordVoteMessageID.RUnlock()
	return calls
}

// ReleaseReminderClaim calls ReleaseReminderClaimFunc.
func (mock *MoqChallenges) ReleaseReminderClaim(context1 context.Context, n int64, time1 time.Time) error {
	callInfo := struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
	}{
		Context1: context1,
		N:        n,
		Time1:    time1,
	}
	mock.lockReleaseReminderClaim.Lock()
	mock.calls.ReleaseReminderClaim = append(mock.calls.ReleaseReminderClaim, callInfo)
	mock.lockReleaseReminderClaim.Unlock()
	if mock.ReleaseReminderClaimFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.ReleaseReminderClaimFunc(context1, n, time1)
}

// ReleaseReminderClaimCalls gets all the calls that were made to ReleaseReminderClaim.
// Check the length with:
//
//	len(mockedchallenges.ReleaseReminderClaimCalls())
func (mock *MoqChallenges) ReleaseReminderClaimCalls() []struct {
	Context1 context.Context
	N        int64
	Time1    time.Time
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
	}
	mock.lockReleaseReminderClaim.RLock()
	calls = mock.calls.ReleaseReminderClaim
	mock.lockReleaseReminderClaim.RUnlock()
	return calls
}

// ReleaseVoteStartClaim calls ReleaseVoteStartClaimFunc.
func (mock *MoqChallenges) ReleaseVoteStartClaim(context1 context.Context, n int64, time1 time.Time) error {
	callInfo := struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
	}{
		Context1: context1,
		N:        n,
		Time1:    time1,
	}
	mock.lockReleaseVoteStartClaim.Lock()
	mock.calls.ReleaseVoteStartClaim = append(mock.calls.ReleaseVoteStartClaim, callInfo)
	mock.lockReleaseVoteStartClaim.Unlock()
	if mock.ReleaseVoteStartClaimFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.ReleaseVoteStartClaimFunc(context1, n, time1)
}

// ReleaseVoteStartClaimCalls gets all the calls that were made to ReleaseVoteStartClaim.
// Check the length with:
//
//	len(mockedchallenges.ReleaseVoteStartClaimCalls())
func (mock *MoqChallenges) ReleaseVoteStartClaimCalls() []struct {
	Context1 context.Context
	N        int64
	Time1    time.Time
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
	}
	mock.lockReleaseVoteStartClaim.RLock()
	calls = mock.calls.ReleaseVoteStartClaim
	mock.lockReleaseVoteStartClaim.RUnlock()
	return calls
}

// SetVoteMessageID calls SetVoteMessageIDFunc.
func (mock *MoqChallenges) SetVoteMessageID(context1 context.Context, n int64, n1 int, time1 time.Time, time11 time.Time) (bool, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		N1       int
		Time1    time.Time
		Time11   time.Time
	}{
		Context1: context1,
		N:        n,
		N1:       n1,
		Time1:    time1,
		Time11:   time11,
	}
	mock.lockSetVoteMessageID.Lock()
	mock.calls.SetVoteMessageID = append(mock.calls.SetVoteMessageID, callInfo)
	mock.lockSetVoteMessageID.Unlock()
	if mock.SetVoteMessageIDFunc == nil {
		var (
			b   bool
			err error
		)
		return b, err
	}
	return mock.SetVoteMessageIDFunc(context1, n, n1, time1, time11)
}

// SetVoteMessageIDCalls gets all the calls that were made to SetVoteMessageID.
// Check the length with:
//
//	len(mockedchallenges.SetVoteMessageIDCalls())
func (mock *MoqChallenges) SetVoteMessageIDCalls() []struct {
	Context1 context.Context
	N        int64
	N1       int
	Time1    time.Time
	Time11   time.Time
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		N1       int
		Time1    time.Time
		Time11   time.Time
	}
	mock.lockSetVoteMessageID.RLock()
	calls = mock.calls.SetVoteMessageID
	mock.lockSetVoteMessageID.RUnlock()
	return calls
}

// StartVoting calls StartVotingFunc.
func (mock *MoqChallenges) StartVoting(context1 context.Context, n int64, time1 time.Time) (bool, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
	}{
		Context1: context1,
		N:        n,
		Time1:    time1,
	}
	mock.lockStartVoting.Lock()
	mock.calls.StartVoting = append(mock.calls.StartVoting, callInfo)
	mock.lockStartVoting.Unlock()
	if mock.StartVotingFunc == nil {
		var (
			b   bool
			err error
		)
		return b, err
	}
	return mock.StartVotingFunc(context1, n, time1)
}

// StartVotingCalls gets all the calls that were made to StartVoting.
// Check the length with:
//
//	len(mockedchallenges.StartVotingCalls())
func (mock *MoqChallenges) StartVotingCalls() []struct {
	Context1 context.Context
	N        int64
	Time1    time.Time
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		Time1    time.Time
	}
	mock.lockStartVoting.RLock()
	calls = mock.calls.StartVoting
	mock.lockStartVoting.RUnlock()
	return calls
}
