// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package scheduler

import (
	"context"
	"sync"
)

// Ensure that MoqPhotoCounter does implement photoCounter.
// If this is not the case, regenerate this file with mockery.
var _ photoCounter = &MoqPhotoCounter{}

// MoqPhotoCounter is a mock implementation of photoCounter.
//
//	func TestSomethingThatUsesphotoCounter(t *testing.T) {
//
//		// make and configure a mocked photoCounter
//		mockedphotoCounter := &MoqPhotoCounter{
//			CountByChallengeFunc: func(context1 context.Context, n int64) (int, error) {
//				panic("mock out the CountByChallenge method")
//			},
//		}
//
//		// use mockedphotoCounter in code that requires photoCounter
//		// and then make assertions.
//
//	}
type MoqPhotoCounter struct {
	// CountByChallengeFunc mocks the CountByChallenge method.
	CountByChallengeFunc func(context1 context.Context, n int64) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// CountByChallenge holds details about calls to the CountByChallenge method.
		CountByChallenge []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
		}
	}
	lockCountByChallenge sync.RWMutex
}

// CountByChallenge calls CountByChallengeFunc.
func (mock *MoqPhotoCounter) CountByChallenge(context1 context.Context, n int64) (int, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
	}{
		Context1: context1,
		N:        n,
	}
	mock.lockCountByChallenge.Lock()
	mock.calls.CountByChallenge = append(mock.calls.CountByChallenge, callInfo)
	mock.lockCountByChallenge.Unlock()
	if mock.CountByChallengeFunc == nil {
		var (
			n1  int
			err error
		)
		return n1, err
	}
	return mock.CountByChallengeFunc(context1, n)
}

// CountByChallengeCalls gets all the calls that were made to CountByChallenge.
// Check the length with:
//
//	len(mockedphotoCounter.CountByChallengeCalls())
func (mock *MoqPhotoCounter) CountByChallengeCalls() []struct {
	Context1 context.Context
	N        int64
} {
	var calls []struct {
		Context1 context.Context
		N        int64
	}
	mock.lockCountByChallenge.RLock()
	calls = mock.calls.CountByChallenge
	mock.lockCountByChallenge.RUnlock()
	return calls
}
