// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package scheduler

import (
	"context"
	"sync"
)

// Ensure that MoqPublisher does implement publisher.
// If this is not the case, regenerate this file with mockery.
var _ publisher = &MoqPublisher{}

// MoqPublisher is a mock implementation of publisher.
//
//	func TestSomethingThatUsespublisher(t *testing.T) {
//
//		// make and configure a mocked publisher
//		mockedpublisher := &MoqPublisher{
//			PinFunc: func(context1 context.Context, n int64, n1 int) error {
//				panic("mock out the Pin method")
//			},
//			SendMarkdownFunc: func(context1 context.Context, n int64, s string) (int, error) {
//				panic("mock out the SendMarkdown method")
//			},
//		}
//
//		// use mockedpublisher in code that requires publisher
//		// and then make assertions.
//
//	}
type MoqPublisher struct {
	// PinFunc mocks the Pin method.
	PinFunc func(context1 context.Context, n int64, n1 int) error

	// SendMarkdownFunc mocks the SendMarkdown method.
	SendMarkdownFunc func(context1 context.Context, n int64, s string) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// Pin holds details about calls to the Pin method.
		Pin []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// N1 is the n1 argument value.
			N1 int
		}
		// SendMarkdown holds details about calls to the SendMarkdown method.
		SendMarkdown []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// S is the s argument value.
			S string
		}
	}
	lockPin          sync.RWMutex
	lockSendMarkdown sync.RWMutex
}

// Pin calls PinFunc.
func (mock *MoqPublisher) Pin(context1 context.Context, n int64, n1 int) error {
	callInfo := struct {
		Context1 context.Context
		N        int64
		N1       int
	}{
		Context1: context1,
		N:        n,
		N1:       n1,
	}
	mock.lockPin.Lock()
	mock.calls.Pin = append(mock.calls.Pin, callInfo)
	mock.lockPin.Unlock()
	if mock.PinFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.PinFunc(context1, n, n1)
}

// PinCalls gets all the calls that were made to Pin.
// Check the length with:
//
//	len(mockedpublisher.PinCalls())
func (mock *MoqPublisher) PinCalls() []struct {
	Context1 context.Context
	N        int64
	N1       int
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		N1       int
	}
	mock.lockPin.RLock()
	calls = mock.calls.Pin
	mock.lockPin.RUnlock()
	return calls
}

// SendMarkdown calls SendMarkdownFunc.
func (mock *MoqPublisher) SendMarkdown(context1 context.Context, n int64, s string) (int, error) {
	callInfo := struct {
		Context1 context.Context
		N        int64
		S        string
	}{
		Context1: context1,
		N:        n,
		S:        s,
	}
	mock.lockSendMarkdown.Lock()
	mock.calls.SendMarkdown = append(mock.calls.SendMarkdown, callInfo)
	mock.lockSendMarkdown.Unlock()
	if mock.SendMarkdownFunc == nil {
		var (
			n1  int
			err error
		)
		return n1, err
	}
	return mock.SendMarkdownFunc(context1, n, s)
}

// SendMarkdownCalls gets all the calls that were made to SendMarkdown.
// Check the length with:
//
//	len(mockedpublisher.SendMarkdownCalls())
func (mock *MoqPublisher) SendMarkdownCalls() []struct {
	Context1 context.Context
	N        int64
	S        string
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		S        string
	}
	mock.lockSendMarkdown.RLock()
	calls = mock.calls.SendMarkdown
	mock.lockSendMarkdown.RUnlock()
	return calls
}
