// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package scheduler

import (
	"context"
	"sync"
)

// Ensure that MoqTopicReporter does implement topicReporter.
// If this is not the case, regenerate this file with mockery.
var _ topicReporter = &MoqTopicReporter{}

// MoqTopicReporter is a mock implementation of topicReporter.
//
//	func TestSomethingThatUsestopicReporter(t *testing.T) {
//
//		// make and configure a mocked topicReporter
//		mockedtopicReporter := &MoqTopicReporter{
//			PublishDueFunc: func(context1 context.Context, n int64, n1 int) error {
//				panic("mock out the PublishDue method")
//			},
//		}
//
//		// use mockedtopicReporter in code that requires topicReporter
//		// and then make assertions.
//
//	}
type MoqTopicReporter struct {
	// PublishDueFunc mocks the PublishDue method.
	PublishDueFunc func(context1 context.Context, n int64, n1 int) error

	// calls tracks calls to the methods.
	calls struct {
		// PublishDue holds details about calls to the PublishDue method.
		PublishDue []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// N1 is the n1 argument value.
			N1 int
		}
	}
	lockPublishDue sync.RWMutex
}

// PublishDue calls PublishDueFunc.
func (mock *MoqTopicReporter) PublishDue(context1 context.Context, n int64, n1 int) error {
	callInfo := struct {
		Context1 context.Context
		N        int64
		N1       int
	}{
		Context1: context1,
		N:        n,
		N1:       n1,
	}
	mock.lockPublishDue.Lock()
	mock.calls.PublishDue = append(mock.calls.PublishDue, callInfo)
	mock.lockPublishDue.Unlock()
	if mock.PublishDueFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.PublishDueFunc(context1, n, n1)
}

// PublishDueCalls gets all the calls that were made to PublishDue.
// Check the length with:
//
//	len(mockedtopicReporter.PublishDueCalls())
func (mock *MoqTopicReporter) PublishDueCalls() []struct {
	Context1 context.Context
	N        int64
	N1       int
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		N1       int
	}
	mock.lockPublishDue.RLock()
	calls = mock.calls.PublishDue
	mock.lockPublishDue.RUnlock()
	return calls
}
