// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package scheduler

import (
	"sync"

	"github.com/TiraelSedai/PhotoChallengeBot/internal/templates"
)

// Ensure that MoqVoteStartRenderer does implement voteStartRenderer.
// If this is not the case, regenerate this file with mockery.
var _ voteStartRenderer = &MoqVoteStartRenderer{}

// MoqVoteStartRenderer is a mock implementation of voteStartRenderer.
//
//	func TestSomethingThatUsesvoteStartRenderer(t *testing.T) {
//
//		// make and configure a mocked voteStartRenderer
//		mockedvoteStartRenderer := &MoqVoteStartRenderer{
//			VoteStartFunc: func(voteStartData templates.VoteStartData) (string, error) {
//				panic("mock out the VoteStart method")
//			},
//		}
//
//		// use mockedvoteStartRenderer in code that requires voteStartRenderer
//		// and then make assertions.
//
//	}
type MoqVoteStartRenderer struct {
	// VoteStartFunc mocks the VoteStart method.
	VoteStartFunc func(voteStartData templates.VoteStartData) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// VoteStart holds details about calls to the VoteStart method.
		VoteStart []struct {
			// VoteStartData is the voteStartData argument value.
			VoteStartData templates.VoteStartData
		}
	}
	lockVoteStart sync.RWMutex
}

// VoteStart calls VoteStartFunc.
func (mock *MoqVoteStartRenderer) VoteStart(voteStartData templates.VoteStartData) (string, error) {
	callInfo := struct {
		VoteStartData templates.VoteStartData
	}{
		VoteStartData: voteStartData,
	}
	mock.lockVoteStart.Lock()
	mock.calls.VoteStart = append(mock.calls.VoteStart, callInfo)
	mock.lockVoteStart.Unlock()
	if mock.VoteStartFunc == nil {
		var (
			s   string
			err error
		)
		return s, err
	}
	return mock.VoteStartFunc(voteStartData)
}

// VoteStartCalls gets all the calls that were made to VoteStart.
// Check the length with:
//
//	len(mockedvoteStartRenderer.VoteStartCalls())
func (mock *MoqVoteStartRenderer) VoteStartCalls() []struct {
	VoteStartData templates.VoteStartData
} {
	var calls []struct {
		VoteStartData templates.VoteStartData
	}
	mock.lockVoteStart.RLock()
	calls = mock.calls.VoteStart
	mock.lockVoteStart.RUnlock()
	return calls
}
