// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package bot

import (
	"context"
	"sync"

	"github.com/go-telegram/bot/models"
)

// Ensure that MoqAdminChatHandler does implement adminChatHandler.
// If this is not the case, regenerate this file with mockery.
var _ adminChatHandler = &MoqAdminChatHandler{}

// MoqAdminChatHandler is a mock implementation of adminChatHandler.
//
//	func TestSomethingThatUsesadminChatHandler(t *testing.T) {
//
//		// make and configure a mocked adminChatHandler
//		mockedadminChatHandler := &MoqAdminChatHandler{
//			HandleAdminChatMessageFunc: func(context1 context.Context, message *models.Message) error {
//				panic("mock out the HandleAdminChatMessage method")
//			},
//		}
//
//		// use mockedadminChatHandler in code that requires adminChatHandler
//		// and then make assertions.
//
//	}
type MoqAdminChatHandler struct {
	// HandleAdminChatMessageFunc mocks the HandleAdminChatMessage method.
	HandleAdminChatMessageFunc func(context1 context.Context, message *models.Message) error

	// calls tracks calls to the methods.
	calls struct {
		// HandleAdminChatMessage holds details about calls to the HandleAdminChatMessage method.
		HandleAdminChatMessage []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// Message is the message argument value.
			Message *models.Message
		}
	}
	lockHandleAdminChatMessage sync.RWMutex
}

// HandleAdminChatMessage calls HandleAdminChatMessageFunc.
func (mock *MoqAdminChatHandler) HandleAdminChatMessage(context1 context.Context, message *models.Message) error {
	callInfo := struct {
		Context1 context.Context
		Message  *models.Message
	}{
		Context1: context1,
		Message:  message,
	}
	mock.lockHandleAdminChatMessage.Lock()
	mock.calls.HandleAdminChatMessage = append(mock.calls.HandleAdminChatMessage, callInfo)
	mock.lockHandleAdminChatMessage.Unlock()
	if mock.HandleAdminChatMessageFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.HandleAdminChatMessageFunc(context1, message)
}

// HandleAdminChatMessageCalls gets all the calls that were made to HandleAdminChatMessage.
// Check the length with:
//
//	len(mockedadminChatHandler.HandleAdminChatMessageCalls())
func (mock *MoqAdminChatHandler) HandleAdminChatMessageCalls() []struct {
	Context1 context.Context
	Message  *models.Message
} {
	var calls []struct {
		Context1 context.Context
		Message  *models.Message
	}
	mock.lockHandleAdminChatMessage.RLock()
	calls = mock.calls.HandleAdminChatMessage
	mock.lockHandleAdminChatMessage.RUnlock()
	return calls
}
