// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package bot

import (
	"context"
	"sync"

	"github.com/go-telegram/bot/models"
)

// Ensure that MoqCallbackQueryHandler does implement callbackQueryHandler.
// If this is not the case, regenerate this file with mockery.
var _ callbackQueryHandler = &MoqCallbackQueryHandler{}

// MoqCallbackQueryHandler is a mock implementation of callbackQueryHandler.
//
//	func TestSomethingThatUsescallbackQueryHandler(t *testing.T) {
//
//		// make and configure a mocked callbackQueryHandler
//		mockedcallbackQueryHandler := &MoqCallbackQueryHandler{
//			HandleCallbackQueryFunc: func(context1 context.Context, callbackQuery *models.CallbackQuery) error {
//				panic("mock out the HandleCallbackQuery method")
//			},
//		}
//
//		// use mockedcallbackQueryHandler in code that requires callbackQueryHandler
//		// and then make assertions.
//
//	}
type MoqCallbackQueryHandler struct {
	// HandleCallbackQueryFunc mocks the HandleCallbackQuery method.
	HandleCallbackQueryFunc func(context1 context.Context, callbackQuery *models.CallbackQuery) error

	// calls tracks calls to the methods.
	calls struct {
		// HandleCallbackQuery holds details about calls to the HandleCallbackQuery method.
		HandleCallbackQuery []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// CallbackQuery is the callbackQuery argument value.
			CallbackQuery *models.CallbackQuery
		}
	}
	lockHandleCallbackQuery sync.RWMutex
}

// HandleCallbackQuery calls HandleCallbackQueryFunc.
func (mock *MoqCallbackQueryHandler) HandleCallbackQuery(context1 context.Context, callbackQuery *models.CallbackQuery) error {
	callInfo := struct {
		Context1      context.Context
		CallbackQuery *models.CallbackQuery
	}{
		Context1:      context1,
		CallbackQuery: callbackQuery,
	}
	mock.lockHandleCallbackQuery.Lock()
	mock.calls.HandleCallbackQuery = append(mock.calls.HandleCallbackQuery, callInfo)
	mock.lockHandleCallbackQuery.Unlock()
	if mock.HandleCallbackQueryFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.HandleCallbackQueryFunc(context1, callbackQuery)
}

// HandleCallbackQueryCalls gets all the calls that were made to HandleCallbackQuery.
// Check the length with:
//
//	len(mockedcallbackQueryHandler.HandleCallbackQueryCalls())
func (mock *MoqCallbackQueryHandler) HandleCallbackQueryCalls() []struct {
	Context1      context.Context
	CallbackQuery *models.CallbackQuery
} {
	var calls []struct {
		Context1      context.Context
		CallbackQuery *models.CallbackQuery
	}
	mock.lockHandleCallbackQuery.RLock()
	calls = mock.calls.HandleCallbackQuery
	mock.lockHandleCallbackQuery.RUnlock()
	return calls
}
