// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package bot

import (
	"context"
	"sync"

	"github.com/go-telegram/bot/models"
)

// Ensure that MoqMainChatHandler does implement mainChatHandler.
// If this is not the case, regenerate this file with mockery.
var _ mainChatHandler = &MoqMainChatHandler{}

// MoqMainChatHandler is a mock implementation of mainChatHandler.
//
//	func TestSomethingThatUsesmainChatHandler(t *testing.T) {
//
//		// make and configure a mocked mainChatHandler
//		mockedmainChatHandler := &MoqMainChatHandler{
//			HandleMainChatMessageFunc: func(context1 context.Context, message *models.Message) error {
//				panic("mock out the HandleMainChatMessage method")
//			},
//		}
//
//		// use mockedmainChatHandler in code that requires mainChatHandler
//		// and then make assertions.
//
//	}
type MoqMainChatHandler struct {
	// HandleMainChatMessageFunc mocks the HandleMainChatMessage method.
	HandleMainChatMessageFunc func(context1 context.Context, message *models.Message) error

	// calls tracks calls to the methods.
	calls struct {
		// HandleMainChatMessage holds details about calls to the HandleMainChatMessage method.
		HandleMainChatMessage []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// Message is the message argument value.
			Message *models.Message
		}
	}
	lockHandleMainChatMessage sync.RWMutex
}

// HandleMainChatMessage calls HandleMainChatMessageFunc.
func (mock *MoqMainChatHandler) HandleMainChatMessage(context1 context.Context, message *models.Message) error {
	callInfo := struct {
		Context1 context.Context
		Message  *models.Message
	}{
		Context1: context1,
		Message:  message,
	}
	mock.lockHandleMainChatMessage.Lock()
	mock.calls.HandleMainChatMessage = append(mock.calls.HandleMainChatMessage, callInfo)
	mock.lockHandleMainChatMessage.Unlock()
	if mock.HandleMainChatMessageFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.HandleMainChatMessageFunc(context1, message)
}

// HandleMainChatMessageCalls gets all the calls that were made to HandleMainChatMessage.
// Check the length with:
//
//	len(mockedmainChatHandler.HandleMainChatMessageCalls())
func (mock *MoqMainChatHandler) HandleMainChatMessageCalls() []struct {
	Context1 context.Context
	Message  *models.Message
} {
	var calls []struct {
		Context1 context.Context
		Message  *models.Message
	}
	mock.lockHandleMainChatMessage.RLock()
	calls = mock.calls.HandleMainChatMessage
	mock.lockHandleMainChatMessage.RUnlock()
	return calls
}
