// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package bot

import (
	"context"
	"sync"

	"github.com/go-telegram/bot/models"
)

// Ensure that MoqPrivateStartHandler does implement privateStartHandler.
// If this is not the case, regenerate this file with mockery.
var _ privateStartHandler = &MoqPrivateStartHandler{}

// MoqPrivateStartHandler is a mock implementation of privateStartHandler.
//
//	func TestSomethingThatUsesprivateStartHandler(t *testing.T) {
//
//		// make and configure a mocked privateStartHandler
//		mockedprivateStartHandler := &MoqPrivateStartHandler{
//			HandlePrivateStartFunc: func(context1 context.Context, message *models.Message, s string) error {
//				panic("mock out the HandlePrivateStart method")
//			},
//		}
//
//		// use mockedprivateStartHandler in code that requires privateStartHandler
//		// and then make assertions.
//
//	}
type MoqPrivateStartHandler struct {
	// HandlePrivateStartFunc mocks the HandlePrivateStart method.
	HandlePrivateStartFunc func(context1 context.Context, message *models.Message, s string) error

	// calls tracks calls to the methods.
	calls struct {
		// HandlePrivateStart holds details about calls to the HandlePrivateStart method.
		HandlePrivateStart []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// Message is the message argument value.
			Message *models.Message
			// S is the s argument value.
			S string
		}
	}
	lockHandlePrivateStart sync.RWMutex
}

// HandlePrivateStart calls HandlePrivateStartFunc.
func (mock *MoqPrivateStartHandler) HandlePrivateStart(context1 context.Context, message *models.Message, s string) error {
	callInfo := struct {
		Context1 context.Context
		Message  *models.Message
		S        string
	}{
		Context1: context1,
		Message:  message,
		S:        s,
	}
	mock.lockHandlePrivateStart.Lock()
	mock.calls.HandlePrivateStart = append(mock.calls.HandlePrivateStart, callInfo)
	mock.lockHandlePrivateStart.Unlock()
	if mock.HandlePrivateStartFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.HandlePrivateStartFunc(context1, message, s)
}

// HandlePrivateStartCalls gets all the calls that were made to HandlePrivateStart.
// Check the length with:
//
//	len(mockedprivateStartHandler.HandlePrivateStartCalls())
func (mock *MoqPrivateStartHandler) HandlePrivateStartCalls() []struct {
	Context1 context.Context
	Message  *models.Message
	S        string
} {
	var calls []struct {
		Context1 context.Context
		Message  *models.Message
		S        string
	}
	mock.lockHandlePrivateStart.RLock()
	calls = mock.calls.HandlePrivateStart
	mock.lockHandlePrivateStart.RUnlock()
	return calls
}
