// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package bot

import (
	"context"
	"sync"
)

// Ensure that MoqWelcomePublisher does implement welcomePublisher.
// If this is not the case, regenerate this file with mockery.
var _ welcomePublisher = &MoqWelcomePublisher{}

// MoqWelcomePublisher is a mock implementation of welcomePublisher.
//
//	func TestSomethingThatUseswelcomePublisher(t *testing.T) {
//
//		// make and configure a mocked welcomePublisher
//		mockedwelcomePublisher := &MoqWelcomePublisher{
//			SendEphemeralMarkdownFunc: func(context1 context.Context, n int64, n1 int64, s string) error {
//				panic("mock out the SendEphemeralMarkdown method")
//			},
//		}
//
//		// use mockedwelcomePublisher in code that requires welcomePublisher
//		// and then make assertions.
//
//	}
type MoqWelcomePublisher struct {
	// SendEphemeralMarkdownFunc mocks the SendEphemeralMarkdown method.
	SendEphemeralMarkdownFunc func(context1 context.Context, n int64, n1 int64, s string) error

	// calls tracks calls to the methods.
	calls struct {
		// SendEphemeralMarkdown holds details about calls to the SendEphemeralMarkdown method.
		SendEphemeralMarkdown []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// N is the n argument value.
			N int64
			// N1 is the n1 argument value.
			N1 int64
			// S is the s argument value.
			S string
		}
	}
	lockSendEphemeralMarkdown sync.RWMutex
}

// SendEphemeralMarkdown calls SendEphemeralMarkdownFunc.
func (mock *MoqWelcomePublisher) SendEphemeralMarkdown(context1 context.Context, n int64, n1 int64, s string) error {
	callInfo := struct {
		Context1 context.Context
		N        int64
		N1       int64
		S        string
	}{
		Context1: context1,
		N:        n,
		N1:       n1,
		S:        s,
	}
	mock.lockSendEphemeralMarkdown.Lock()
	mock.calls.SendEphemeralMarkdown = append(mock.calls.SendEphemeralMarkdown, callInfo)
	mock.lockSendEphemeralMarkdown.Unlock()
	if mock.SendEphemeralMarkdownFunc == nil {
		var (
			err error
		)
		return err
	}
	return mock.SendEphemeralMarkdownFunc(context1, n, n1, s)
}

// SendEphemeralMarkdownCalls gets all the calls that were made to SendEphemeralMarkdown.
// Check the length with:
//
//	len(mockedwelcomePublisher.SendEphemeralMarkdownCalls())
func (mock *MoqWelcomePublisher) SendEphemeralMarkdownCalls() []struct {
	Context1 context.Context
	N        int64
	N1       int64
	S        string
} {
	var calls []struct {
		Context1 context.Context
		N        int64
		N1       int64
		S        string
	}
	mock.lockSendEphemeralMarkdown.RLock()
	calls = mock.calls.SendEphemeralMarkdown
	mock.lockSendEphemeralMarkdown.RUnlock()
	return calls
}
